<?php
session_start();
?>
<script src="../js/JQuery/jquery-1.11.1.min.js"></script><!--sempre chamar, com jquery ui o $ajax não funciona-->
<script src="../js/JQuery/jquery-ui-1.11.2.custom/jquery-ui.js"></script><!--sempre chamar, com jquery ui o $ajax não funciona-->
<script>
    $(document).ready(function () {

        $('#empresa').change(function () {
            $('#estabelecimento').load('../Controller/combo_estabelecimento2016.php?empresa=' + $('#empresa').val());
        });

        $('#button').css("display", "none");
        $('#datadoperiodico').css("display", "none");
        
        var esportes = [
		"1 - B001 SUPER CASA AMARELA","2 - B002 TODO DIA CARPINA","4 - B004 SUPER PARQUE AMORIM","5 - B005  SUPER ARRUDA I",
                "6 - B006  SUPER BOA VIAGEM I","7 - B007  TODO DIA AFOGADOS","9 - B009  HIPER CAXANGA","10 - B010  SUPER CASA CAIADA",
                "14 - B014  HIPER BUARQUE DE MACEDO","16 - B016 SUPER CASTRO PINTO","17 - B017  SUPER AFLITOS","18 - B018  SUPER CEASA MACEIO",
                "19 - B019  SUPER PIEDADE","20 - B020  HIPER CAMPINA GRANDE","21 - B021  SUPER PAJUCARA","22 - B022  SUPER FAROL",
                "23 - B023  SUPER BOMPRECO MERCADO","27 - B027 SUPER PONTA VERDE","28 - B028  SUPER CAMPINA GRANDE II","29 - B029  HIPER MIRANTE",
                "31 - B031  SUPER BENFICA","33 - B033  SUPER EPITACIO PESSOA","34 - B034  HIPER JOAO PESSOA","35 - B035  SUPER BOA VIAGEM II",
                "37 - B037  HIPER LAGOA","38 - B038  SUPER MANAIRA","39 - B039 TODO DIA CRUZ DAS ARMAS","40 - B040 TODO DIA RIO DOCE",
                "41 - B041  SUPER SHOPPING CENTER","43 - B043 SUPER COCO","44 - B044 TODO DIA GOIANA","46 - B046 TODO DIA SANTA RITA",
                "48 - B048 TODO DIA BAYEUX","49 - B049 TODO DIA GARANHUNS","58 - B058  TODO DIA PAULISTA","63 - B063 TODO DIA CAMPINA GRANDE",
                "68 - B068 SUPER ALDEOTA","70 - B070 CD MARANHAO","72 - B072 TODO DIA GRAVATA","73 - B073 SUPER VERMELHO",
                "74 - B074 SUPER PONTA NEGRA","93 - B093  MAGAZINE RECIFE","94 - B094  HIPER FORTALEZA","96 - B096  HIPER GUARARAPES",
                "102 - B102  HIPER BEZERRA DE MENEZES","105 - B105 SUPER DIONISIO TORRES","106 - B106 TODO DIA IGARASSU","109 - B109 TODO DIA BANCARIO",
                "118 - B118 HIPER FATIMA","121 - B121  HIPER NATAL","122 - B122  HIPER PONTA NEGRA I","126 - B126  SUPER APICUM",
                "128 - B128  SUPER COHAB","130 - B130  SUPER OURIQUE","131 - B131  SUPER JABOATAO","132 - B132  SUPER SAO FRANCISCO",
                "134 - B134  SUPER OLHO D AGUA","136 - B136 TODO DIA AGUAS COMPRIDAS","137 - B137 TODO DIA NOVA DESCOBERTA","140 - B140  HIPER CALHAU",
                "144 - B144  HIPER MOSSORO","145 - B145  SUPER TERESINA","159 - B159  TODO DIA CAMARAGIBE","160 - B160  SUPER JANGA",
                "166 - B166 TODO DIA CAVALEIRO I","214 - B214  TODO DIA CABO","256 - B256  SUPER CANDEIAS","266 - B266 CEDIM MURIBECA",
"270 - B270  HIPER FAROL","271 - B271  HIPER JATIUCA","297 - B297  MAGAZINE SHOPPING IGUATE","310 - B310  HIPER CASA FORTE",
"313 - B313 HIPER JUAZEIRO DO NORTE","314 - B314  HIPER TERESINA II","315 - B315 HIPER BOMPRECO WASHINGTON","320 - B320 HIPER AV RECIFE",
"321 - B321 TODO DIA PEIXINHOS","327 - B327  TODO DIA SAO LOURENCO II","328 - B328  TODO DIA ABREU E LIMA","330 - B330  TODO DIA PRAZERES",
"333 - B333 TODO DIA VITORIA DE SANTO","334 - B334  TODO DIA AREIAS","337 - B337  HIPER TACARUNA","339 - B339  HIPER CARUARU",
"341 - B341  HIPER BOA VIAGEM","347 - B347 FARMACIA AFOGADOS","350 - B350 HIPER OLINDA","352 - B352  SUPER  ESPINHEIRO",
"355 - B355  HIPER TERESINA","361 - B361  SUPER PETROLINA","371 - B371 FARMACIA PARQUE AMORIM","379 - B379 FARMACIA  PRAZERES",
"393 - B393 FARMACIA AV RECIFE","397 - B397  HIPER PETROLINA","407 - B407 TODO DIA TURU","408 - B408 HIPER ANTARES",
"409 - B409 SUPER TODO DIA PENEDO","424 - B424 FARMACIA OLINDA","445 - B445 TODO DIA VARGEM GRANDE","446 - B446 TODO DIA N S DA GLORIA",
"447 - B447 TODO DIA IPOJUCA","453 - B453 TODO DIA LIMOEIRO","455 - B455 TODO DIA BARRA DE JANGADA","456 - B456 TODO DIA GEISEL",
"458 - B458 TODO DIA SANTA LUCIA","459 - B459 TODO DIA CLIMA BOM","460 - B460 TODO DIA JARDIM PIEDADE","461 - B461 TODO DIA ARAPIRACA",
"462 - B462 TODO DIA ARAPIRACA II","463 - B463 TODO DIA JACINTINHO","465 - B465 TODO DIA BAIRRO DOS ESTAD","466 - B466 TODO DIA PALMEIRA DOS IND",
"467 - B467 TODO DIA TIMBI","469 - B469 TODO DIA BULTRINS","472 - B472 TODO DIA SURUBIM","473 - B473 TODO DIA SANTANA DO IPANE",
"474 - B474 TODO DIA CABEDELO","476 - B476 TODO DIA PEDRAS DE FOGO","477 - B477 TODO DIA PRATA","478 - B478 TODO DIA BEZERROS",
"479 - B479 TODO DIA TIMBAUBA","481 - B481 TODO DIA VILLAGE CAMPESTR","482 - B482 TODO DIA PESQUEIRA","483 - B483 TODO DIA MAMANGUAPE",
"486 - B486 TODO DIA GAMELEIRA","487 - B487 TODO DIA ABREU E LIMA III","488 - B488 TODO DIA ESCADA","490 - B490 TODO DIA BELO JARDIM",
"491 - B491 TODO DIA PAU AMARELO","492 - B492 TODO DIA VILA RICA","493 - B493 TODO DIA SAPE","494 - B494 TODO DIA NAZARE DA MATA",
"495 - B495 TODO DIA UNIAO DOS PALMAR","496 - B496 TODO DIA CORURIPE","497 - B497 TODO DIA TEOTONIO VILELA","498 - B498 TODO DIA JARDIM SAO CRIST",
"499 - B499 TODO DIA ARARI","502 - B502 TODO DIA CAMACARI","103 - B503  SUPER POLITEAMA","504 - B504  SUPER JARDINS",
"505 - B505 TODO DIA CASTELO BRANCO","506 - B506 TODO DIA SAO CRISTOVAO","510 - B510  HIPER JARDINS","510 - B510  HIPER JARDINS",
"411 - B511 SUPER BOA VISTA DE BROTAS","312 - B512  TODO DIA LIBERDADE","213 - B513  SUPER LARGO DO PAPAGAIO","314 - B514  SUPER PITUBA",
"115 - B515  SUPER CHAME-CHAME","517 - B517 HIPER ROTULA","318 - B518  SUPER NAZARE","520 - B520  HIPER BONOCO",
"421 - B521  SUPER CAMPINAS DE BROTAS","522 - B522  SUPER SH SALVADOR","323 - B523  TODO DIA  RODOVIARIA","324 - B524 SUPER  IAPI",
"125 - B525  SUPER CANELA","28 - B528  HIPER IGUATEMI","229 - B529  SUPER BOM DESPACHO","430 - B530 SUPER SAO RAFAEL",
"531 - B531 TODO DIA SUSSUARANA","532 - B532 TODO DIA URUGUAI","533 - B533 TODO DIA SAO CAETANO","535 - B535 TODO DIA MAL RONDON",
"537 - B537 TODO DIA ALAGOINHAS","538 - B538 TODO DIA TANCREDO NEVES","539 - B539 TODO DIA CRUZ DAS ALMAS","40 - B540  HIPER FEIRA DE SANTANA",
"541 - B541 TODO DIA STO ANTONIO DE J","443 - B543  TODO DIA PARIPE","352 - B552 SUPER FONTE NOVA","154 - B554  SUPER RIO VERMELHO",
"156 - B556  SUPER BOCA DO RIO","158 - B558  SUPER ITAPOAN","459 - B559  TODO DIA PERNAMBUES","360 - B560 SUPER SAO CAETANO",
"362 - B562  SUPER ITAIGARA","63 - B563  HIPER GARIBALDI","64 - B564  HIPER CABULA","265 - B565  SUPER CAMACARI",
"270 - B570  TODO DIA SIMOES FILHO","171 - B571  SUPER BARRA AVENIDA","472 - B572  TODO DIA  PERIPERI","475 - B575  TODO DIA COSME DE FARIAS",
"476 - B576  SUPER PAU DA LIMA","577 - B577  HIPER LITORAL NORTE","578 - B578  SUPER JARDIM ARMACAO","579 - B579  SUPER VASCO DA GAMA",
"580 - B580  SUPER MANOEL DIAS","581 - B581  SUPER MATATU BROTAS","582 - B582  SUPER BARRA","84 - B584  HIPER VITORIA DA CONQUIS",
"585 - B585  HIPER ITABUNA","286 - B586  TODO DIA DIAS DAVILA","487 - B587 SUPER LAURO DE FREITAS","289 - B589  SUPER PLATAFORMA",
"593 - B593  HIPER ARACAJU","595 - B595  SUPER SANEAMENTO","596 - B596  SUPER RODOVIARIA","498 - B598 SUPER  CANDEIAS",
"599 - B599  SUPER SIQUEIRA CAMPOS SE","602 - B602 TODO DIA CIDADE NOVA","603 - B603 TODO DIA LAGARTO","604 - B604 TODO DIA ESTANCIA",
"606 - B606  TODO DIA FAZENDA GRANDE","607 - B607 TODO DIA SANTO AMARO","608 - B608 TODO DIA SAO CONRADO","609 - B609 TODO DIA N S DO SOCORRO",
"611 - B611 TODO DIA BUGIO","612 - B612 TODO DIA PROPRIA","613 - B613 TODO DIA TOMBA","614 - B614 TODO DIA KALILANDIA",
"615 - B615 TODO DIA SR DOS PASSOS","616 - B616 TODO DIA SERRINHA","617 - B617 TODO DIA SANTO ESTEVAO","618 - B618 TODO DIA VALENCA",
"619 - B619 TODO DIA AGUAS CLARAS","620 - B620 TODO DIA CIA I","621 - B621 TODO DIA CARLOS GOMES","622 - B622 TODO DIA AMARGOSA",
"623 - B623 TODO DIA MATA ESCURA","624 - B624 TODO DIA VERA CRUZ","625 - B625 TODO DIA ESPLANADA","626 - B626 TODO DIA POJUCA",
"632 - B632 TODO DIA CASTRO ALVES","633 - B633 TODO DIA SAO GONCALO DOS","634 - B634 TODO DIA ENTRE RIOS","635 - B635 TODO DIA BOQUIM",
"636 - B636 TODO DIA MATA DE SAO JOAO","637 - B637 TODO DIA MURITIBA","638 - B638 TODO DIA ITABERABA","640 - B640 TODO DIA MORENO",
"641 - B641 TODO DIA BAIXA DE QUINTAS","642 - B642 TODO DIA PIRAJA","643 - B643 TODO DIA VALERIA","644 - B644 TODO DIA RIO REAL",
"645 - B645 TODO DIA CASTELO BRANCO","646 - B646 TODO DIA CAMACARI","647 - B647 TODO DIA DIAS D AVILA II","648 - B648 SUPER TD CONCEICAO COITE",
"649 - B649 TODO DIA SANTA RITA","651 - B651 TODO DIA ESTRADA BARREIRA","660 - B660 CENTRAL DE PADARIA BAHIA","888 - B888 ESC REG RECIFE",
"85 - BIG 003 FLORIANOPOLIS CAPOEIRAS C0003","86 - BIG 004 JOINVILLE AMERICA C0406","5 - BIG 005 R.GRANDE SEN.CORREA C0506",
"80 - BIG 006 CTBA AV. DAS TORRES C0606","87 - BIG 007 POA CRISTAL C0706","89 - BIG 010 CACHOEIRINHA F.CUNHA 4000 C1066","18 - BIG 018 N.HAMBURGO N.BECKER C1806",
"25 - BIG 025.MARIA N.SRA.LOURDES C0025","412 - BIG 044 CTBA PORTAO C0044","414 - BIG 047 MARINGA TUIUTI C0047","416 - BIG 053 CTBA B.VISTA C0053",
"417 - BIG 055 CTBA XAXIM 2973 C0055","437 - BIG 071 CTBA STA.FELICIDADE C0071","101 - BIG 075 CANOAS G.SCHELL 9000 C0075","454 - BIG 076 FOZ JK DE OLIVEIRA C0076","92 - BIG 079 POA SERTORIO C0079",
"83 - BIG 083 S.LEOPOLDO PINHEIRO C0083","438 - BIG 090 CTBA PINHEIRINHO C0090","82 - BIG 091 ALVORADA AGUA VIVA C0091","920 - BIG 092 CAXIAS M.HERVAL","107 - BIG 096 VIAMAO S.CECILIA C0966",
"105 - BIG 097 JOINVILLE A.GARIBALDI C0097","109 - BIG 123 BLUMENAU BAIRRO DA VELHA C0123","548 - BIG 150 LIVRAMENTO C0150","553 - BIG 155 URUGUAIANA D.CAXIAS C0155","117 - BIG 200 CAMBORIU C0200",
"111 - BIG 202 PELOTAS C0202","114 - BIG 205 ESTEIO CENTRO C0205","122 - BIG 208 GRAVATAI C1059","121 - BIG 209 IGUATEMI C1038","125 - BIG 210 POA ZONA SUL C1043",
"224 - BIG 271 MARINGA PR C1255","225 - BIG 299 UMUARAMA PR C1325","231 - BIG 310 SANTA CRUZ RS C1346","199 - BIG 336 BRUSQUE SC C1365","240 - BIG 341 SAPIRANGA C1394","312 - BIG 354 CAMPO MOURAO PR C1449",
"257 - BIG 375 BLUMENAU C1475","263 - BIG 382 BAGE C1512","264 - BIG 383 TOLEDO PR C1511","269 - BIG 385 SANTA MARIA PATRONATO C1526","268 - BIG 394 CHAPECO C1559","270 - BIG 396 LAGES C1606",
"424 - BIG 862 P.GROSSA UVARAMAS C0862","98 - CD 400 POA RS","7418 - CD 418 PINHAIS PR","120 - CD 425 MAXXI ATACADO","132 - CD 427 MAXXI RECIFE","141 - CD 428 MAXXI EMBU",
"172 - CD 430 NOVA SANTA RITA RS","256 - CD 431 MAXXI SALVADOR","7049 - CD DE EQUIPAMENTOS","250 - CD MAXXI 433 CAMBORIU SC","1 - CD PIRAJA BA","7491 - CENTRO DE DISTR ECOM RECIFE",
"7479 - CENTRO DE DISTRIBUICAO FARMA","7457 - CENTRO DISTRIBUICAO BARUERI","7472 - CENTRO DISTRIBUICAO BETIM","7475 - CENTRO DISTRIBUICAO BETIM","7476 - CENTRO DISTRIBUICAO CAJAMAR","7456 - CENTRO DISTRIBUICAO CONDE",
"4995 - CENTRO DISTRIBUICAO EMBU","7477 - CENTRO DISTRIBUICAO VESPASIANO","96 - CP 402 POA RS","110 - CP 424 ESTEIO VT PORTO","307 - DEPOSITO DOX            F","4516 - DROGARIA HIPER ANTARES",
"4602 - DROGARIA HIPER TAUBATE","4592 - DROGARIA HTD VITORIA  STO ANTÃ","4660 - DROGARIA HTD VITORIA S LOURENC","4220 - DROGARIA SC CAMPO GRANDE","4372 - DROGARIA SUPER VITORIA","4514 - DROGARIA WM SUMARE",
"142 - ESCRITORIO MAXXI 410 BARUERI C9282","434 - ESCRITORIO REGIONAL 417 CTBA C9282","91 - ESCRITORIO REGIONAL PORTO ALEGRE C9282","4382 - FAMARCIA BIG PELOTAS","4288 - FAMARCIA MAXXI PELOTAS","4304 - FARMACIA AMERICANA",
"4305 - FARMACIA ARARAS","4348 - FARMACIA ASA NORTE","4507 - FARMACIA BIG BAGE","4381 - FARMACIA BIG BLUMENAU","4407 - FARMACIA BIG BRUSQUE","4408 - FARMACIA BIG CAMPO MOURAO","4387 - FARMACIA BIG CAPOEIRAS",
"4283 - FARMACIA BIG CAXIAS DO SUL","4599 - FARMACIA BIG CHAPECO","4284 - FARMACIA BIG GRAVATAI","4386 - FARMACIA BIG JK FOZ DO IGUACU","4588 - FARMACIA BIG JOINVILLE","4509 - FARMACIA BIG LONDRINA","4397 - FARMACIA BIG MARINGA CATUAI",
"4373 - FARMACIA BIG PINHEIRINHO","4587 - FARMACIA BIG SANTA CRUZ","4292 - FARMACIA BIG SANTA MARIA","4295 - FARMACIA BIG SAO LEOPOLDO","4597 - FARMACIA BIG SAPIRANGA","4289 - FARMACIA BIG SERTORIO","4610 - FARMACIA BIG STA MARIA PATRONA",
"4506 - FARMACIA BIG TOLEDO","4375 - FARMACIA BIG UMUARAMA","4296 - FARMACIA BIG URUGUAIANA","4291 - FARMACIA BIG ZONA SUL","4274 - FARMACIA CAMPOS DOS GOYTACAZES","4312 - FARMACIA DIADEMA","4212 - FARMACIA GOIANIA NORTE",
"4323 - FARMACIA GRANJA VIANA","4185 - FARMACIA HBP  CABULA","4264 - FARMACIA HBP AV RECIFE","4228 - FARMACIA HBP BESSA","4208 - FARMACIA HBP BEZERRA MENEZES","4266 - FARMACIA HBP BOA VIAGEM","4169 - FARMACIA HBP BONOCO",
"4150 - FARMACIA HBP BUARQUE DE MACEDO","4224 - FARMACIA HBP CAMPINA GRANDE","4263 - FARMACIA HBP CASA FORTE","4154 - FARMACIA HBP FAROL II","4161 - FARMACIA HBP FEIRA DE SANTANA","4184 - FARMACIA HBP GARIBALDI",
"4239 - FARMACIA HBP GUARARAPES","4173 - FARMACIA HBP IGUATEMI","4162 - FARMACIA HBP ITABUN","4534 - FARMACIA HBP JATIUCA","4493 - FARMACIA HBP JUAZEIRO NORTE","4227 - FARMACIA HBP LAGOA","4281 - FARMACIA HBP LAGOA NOVA",
"4163 - FARMACIA HBP LITORAL NORTE","4223 - FARMACIA HBP MIRANTE","4543 - FARMACIA HBP MOSSORO","4247 - FARMACIA HBP OLINDA","4207 - FARMACIA HBP PLANALTO","4279 - FARMACIA HBP PONTA NEGRA","4581 - FARMACIA HBP ROTULA",
"4217 - FARMACIA HBP SAO LUIZ","4270 - FARMACIA HBP TERESINA","4376 - FARMACIA HBP TERESINA II","4206 - FARMACIA HBP VITORIA CONQUISTA","4300 - FARMACIA HIPER ARACAJU",
"4517 - FARMACIA HIPER ASSIS","4272 - FARMACIA HIPER AVENIDA PARANA","4515 - FARMACIA HIPER CATANDUVA","4255 - FARMACIA HIPER CAXANGA","4605 - FARMACIA HIPER INDAIATUBA",
"4299 - FARMACIA HIPER JARDINS","4317 - FARMACIA HIPER MOGI GUACU","4508 - FARMACIA HIPER PASSOS","4511 - FARMACIA HIPER PATOS DE MINAS","4251 - FARMACIA HIPER PETROLINA",
"4319 - FARMACIA HIPER SANTO ANDRE","4234 - FARMACIA HIPER SHOP CARUARU","4265 - FARMACIA HIPER TACARUNA","4368 - FARMACIA HIPER VOLTA REDONDA","4384 - FARMACIA HIPERMERCADO TORRES","4611 - FARMACIA HTD PAULISTA MARANG.",
"4400 - FARMACIA INDIANOPOLIS","4315 - FARMACIA LIMEIRA","4339 - FARMACIA MACAE","4479 - FARMACIA MAXXI BAURU","4297 - FARMACIA MAXXI ITAJAI","4218 - FARMACIA MAXXI LAGES","4566 - FARMACIA MAXXI LAJEADO",
"4164 - FARMACIA MAXXI LAURO FREITAS","4287 - FARMACIA MAXXI NOVO HAMBURGO","4497 - FARMACIA MAXXI VIAMAO","4325 - FARMACIA MORUMBI","4282 - FARMACIA NAC BENTO GONCALVES","4285 - FARMACIA NAC GRAVATAI",
"4290 - FARMACIA NAC LUCAS DE OLIVEIRA","4294 - FARMACIA NACIONAL FLORENCIO AB","4286 - FARMACIA NACIONAL IMBE","4578 - FARMACIA NACIONAL TERESOPOLIS","4483 - FARMACIA PRESIDENTE PRUDENTE",
"4320 - FARMACIA S JOSE DO RIO PRETO","4321 - FARMACIA SAO JOSE DOS CAMPOS","4172 - FARMACIA SBP  CANELA","4167 - FARMACIA SBP  PITUBA","4188 - FARMACIA SBP  VASCO DA GAMA","4491 - FARMACIA SBP ALDEOTA",
"4213 - FARMACIA SBP APICUM","4187 - FARMACIA SBP ARMACAO","4194 - FARMACIA SBP BARRA","4280 - FARMACIA SBP BARRO VERMELHO","4201 - FARMACIA SBP BOCA DO RIO","4200 - FARMACIA SBP BOM DESPACHO","4158 - FARMACIA SBP CAMACARI",
"4222 - FARMACIA SBP CAMPINA GRANDE II","4170 - FARMACIA SBP CAMPINAS DE BROTA","4159 - FARMACIA SBP CANDEIAS","4225 - FARMACIA SBP CASTRO PINTO","4156 - FARMACIA SBP CEASA","4168 - FARMACIA SBP CHAME CHAME","4489 - FARMACIA SBP COCO",
"4214 - FARMACIA SBP COHAB","4226 - FARMACIA SBP EPITACIO PESSOA","4261 - FARMACIA SBP ESPINHEIRO","4152 - FARMACIA SBP FAROL I","4179 - FARMACIA SBP FONTE NOVA","4269 - FARMACIA SBP FREI SERAFIM",
"4171 - FARMACIA SBP IAPI","4183 - FARMACIA SBP ITAIGARA","4181 - FARMACIA SBP ITAPUA","4241 - FARMACIA SBP JABOATAO","4166 - FARMACIA SBP LARGO DO PAPAGAIO","4189 - FARMACIA SBP MATATU DO BROTAS",
"4191 - FARMACIA SBP NAZARE","4216 - FARMACIA SBP OLHOS D AGUA","4151 - FARMACIA SBP PAJUCARA","4262 - FARMACIA SBP PARQUE AMORIM","4195 - FARMACIA SBP PLATAFORMA","4196 - FARMACIA SBP POLITEAMA","4182 - FARMACIA SBP SAO CAETANO",
"4215 - FARMACIA SBP SAO FRANCISCO","4174 - FARMACIA SBP SAO RAFAEL","4198 - FARMACIA SBP SHOPPING SALVADOR","4153 - FARMACIA SBP0PONTA VERDE","4409 - FARMACIA SC FATIMA","4353 - FARMACIA SC MARILIA",
"4482 - FARMACIA SC PAMPULHA","4318 - FARMACIA SC PIRACICABA","4308 - FARMACIA SC SHOPPING DOM PEDRO","4309 - FARMACIA SC SHOPPING OUTLET","4401 - FARMACIA SC SOROCABA","4533 - FARMACIA SC VILA GUILHERME",
"4477 - FARMACIA SC W SOARES","4601 - FARMACIA STD PENEDO","4260 - FARMACIA SUPER AFLITOS","4352 - FARMACIA SUPER AGUAS CLARAS","4256 - FARMACIA SUPER BENFICA","4253 - FARMACIA SUPER BOA VIAGEM",
"4237 - FARMACIA SUPER CANDEIAS","4259 - FARMACIA SUPER CASA AMARELA","4257 - FARMACIA SUPER DOMIN FERREIRA","4248 - FARMACIA SUPER JANGA","4298 - FARMACIA SUPER JARDINS","4250 - FARMACIA SUPER PETROLINA",
"4240 - FARMACIA SUPER PIEDADE","4301 - FARMACIA SUPER SANEAMENTO","4258 - FARMACIA SUPER SHOPPING RECIFE","4303 - FARMACIA SUPER SIQUEIRA CAMPOS","4252 - FARMACIA SUPERC ARRUDA I","4307 - FARMACIA SUPERCENTER BAURU",
"4598 - FARMACIA SUPERCENTER BRASILIA","4313 - FARMACIA SUPERCENTER FRANCA","4388 - FARMACIA SUPERCENTER GOIANIA","4314 - FARMACIA SUPERCENTER GUARULHOS","4350 - FARMACIA SUPERCENTER ITU","4406 - FARMACIA SUPERCENTER JACAREI",
"4371 - FARMACIA SUPERCENTER SAO BERNA","4306 - FARMACIA TAMBORE","4231 - FARMACIA TD  CABO","4199 - FARMACIA TD  RODOVIARIA","4230 - FARMACIA TD ABREU E LIMA","4254 - FARMACIA TD AFOGADOS",
"4392 - FARMACIA TD ALTO DO BOQUEIRAO","4157 - FARMACIA TD CAMACARI","4232 - FARMACIA TD CAMARAGIBE","4328 - FARMACIA TD CAMPANARIO","4538 - FARMACIA TD CAMPO BOM","4558 - FARMACIA TD CANOAS EST VELHA",
"4568 - FARMACIA TD CANUDOS I","4233 - FARMACIA TD CARPINA","4197 - FARMACIA TD CASTELO BRANCO","4242 - FARMACIA TD CAVALEIRO","4563 - FARMACIA TD CIA I","4160 - FARMACIA TD CRUZ DAS ALMAS",
"4190 - FARMACIA TD DIAS DAVILA","4430 - FARMACIA TD ESPLANADA","4579 - FARMACIA TD GOIANA","4236 - FARMACIA TD IGARASSU","4418 - FARMACIA TD LAGARTO","4395 - FARMACIA TD LAPA",
"4165 - FARMACIA TD LIBERDADE","4433 - FARMACIA TD MAMANGUAPE","4177 - FARMACIA TD MARECHAL RONDON","4178 - FARMACIA TD PARIPE","4249 - FARMACIA TD PAULISTA","4571 - FARMACIA TD PEDRAS DE FOGO",
"4186 - FARMACIA TD PERIPERI","4193 - FARMACIA TD PERNAMBUES","4586 - FARMACIA TD PESQUEIRA","4590 - FARMACIA TD POJUCA","4396 - FARMACIA TD PONTA GROSSA","4238 - FARMACIA TD PRAZERES II","4243 - FARMACIA TD RIO DOCE",
"4344 - FARMACIA TD ROSEIRA PARK","4229 - FARMACIA TD SANTA RITA","4550 - FARMACIA TD SANTANA DO IPANEMA","4555 - FARMACIA TD SANTO AMARO","4541 - FARMACIA TD SANTO ESTEVAO","4176 - FARMACIA TD SAO CAETANO","4416 - FARMACIA TD SAO CRISTOVAO",
"4267 - FARMACIA TD SAO LOURENCO II","4542 - FARMACIA TD SENHOR DOS PASSOS","4540 - FARMACIA TD SERRINHA","4205 - FARMACIA TD SIMOES FILHO","4175 - FARMACIA TD SUSSUARANA","4268 - FARMACIA TD VITORIA STO ANTAO",
"4423 - FARMACIA TODO DIA PROPRIA","4354 - FARMACIA UBERABA","4398 - FARMACIA UBERLANDIA","4324 - FARMACIA VL LEOPOLDINA","4322 - FARMACIA WASHINGTON LUIS","549 - FRIGONAL 414 MONTENEGRO RS","1596 - HIPER INDAIATUBA",
"1567 - HIPER TAUBATE","302 - HIPER TD SAO LOURENCO DA MATA","448 - HIPER TD VITORIA DE STO ANTAO","307 - HIPER TODO DIA PAULISTA","9282 - HO","9 - LOJA 09 - PARANAGUA     F",
"52 - LOJA 52 - CURITIBA      F","427 - MAXXI 059 CTBA JD.AMERICA 1450","511 - MAXXI 112 CANOAS TABAI C1575","518 - MAXXI 120 S.MARIA A.BOLSON C1576","534 - MAXXI 136 S.CRUZ BR 471 C1577","562 - MAXXI 164 POA SARANDI C1578",
"565 - MAXXI 168 R.GRANDE PARQUE C1579","573 - MAXXI 177 GRAVATAI S.GERALDO C1591","590 - MAXXI 196 CAXIAS S.JOSE C1580","116 - MAXXI 203 DISTRIBUICAO POA","113 - MAXXI 204 FLORIANOPOLIS C1581","123 - MAXXI 212 ITAJAI C1058",
"124 - MAXXI 216 NOVO HAMBURGO C1057","135 - MAXXI 218 PELOTAS C1097","152 - MAXXI 223 VIAMAO C1131","136 - MAXXI 224 MARAPONGA C1084","130 - MAXXI 227 LAURO DE FREITAS BA C1594","137 - MAXXI 228 MARES C1077",
"138 - MAXXI 229 DIADEMA C1092","144 - MAXXI 230 CAMPO GRANDE C1102","140 - MAXXI 232 LONDRINA C1103","133 - MAXXI 237 TABOAO DA SERRA C1129","143 - MAXXI 240 PAU DA LIMA C1132","161 - MAXXI 246 ALAGOAS C1156",
"146 - MAXXI 247 SAPOPEMBA","171 - MAXXI 249 JOINVILLE","158 - MAXXI 250 LAGES C1295","163 - MAXXI 251 FOZ DO IGUACU","170 - MAXXI 253 ARAPIRACA AL C1220","164 - MAXXI 254 MARACANAU CE C1221",
"155 - MAXXI 255 FEIRA DE SANTANA BA C1223","162 - MAXXI 256 CAMPINA GRANDE PB C1222","159 - MAXXI 257 CHAPECO SC C1218","188 - MAXXI 259 BAURU/SP","150 - MAXXI 261 MARILIA","178 - MAXXI 264 CAMPO GRANDE SUL C1197",
"153 - MAXXI 265 MONTES CLAROS MG","198 - MAXXI 266 CABO SANTO AGOSTINHO/PE C1240","165 - MAXXI 268 CRICIUMA C1252","192 - MAXXI 269 VITORIA DA CONQUISTA/BA C1253","177 - MAXXI 272 RIO CLARO/SP","176 - MAXXI 276 PINHAIS/PR C1265",
"168 - MAXXI 277 VALPARAISO DE GOIAS GO C1278","154 - MAXXI 281 OLINDA PE C1593","193 - MAXXI 283 LAJEADO/RS C1287","259 - MAXXI 285 FAZENDINHA C1295","234 - MAXXI 311 GUARAPUAVA PR C1347",
"230 - MAXXI 318 SANTO ANGELO RS C1358","262 - MAXXI 319 ITABUNA C1359","229 - MAXXI 321 ERECHIM RS","232 - MAXXI 337 TERESINA PI C1366","238 - MAXXI 338 PARNAMIRIM C1367","255 - MAXXI 347 JUAZEIRO DO NORTE CE C1433","251 - MAXXI 359 PIRACICABA SP C1462",
"252 - MAXXI 363 SANTA BARBARA SP C1463","265 - MAXXI 365 RIBEIRAO DAS NEVES C1467","266 - MAXXI 369 MOSSORO RN C1471","267 - MAXXI 370  PRESIDENTE PRUDENTE C1472","301 - MAXXI 819 POA HUMAITA C1582","421 - MAXXI 852 CTBA BOQUEIRAO C1592",
"401 - MERCADORAMA 035 CTBA COM.ARAUJO C3506","403 - MERCADORAMA 036 CTBA XV DE NOV. C0036","404 - MERCADORAMA 038 CTBA TIRADENTES C3806","405 - MERCADORAMA 039 CTBA GEN.OSORIO C0039","406 - MERCADORAMA 041 CTBA S.JARDIM","409 - MERCADORAMA 042 CTBA JUVEVE C0042",
"410 - MERCADORAMA 043 CTBA BIGORRILHO C0043","413 - MERCADORAMA 046 CTBA JDAMERICAS C0046","415 - MERCADORAMA 051 CTBA SEMINARIO C0051","428 - MERCADORAMA 060 CTBA ALTO DA XV C0060","429 - MERCADORAMA 061 CTBA N.MUNDO C0061","430 - MERCADORAMA 063 SJPINHAIS C0063",
"431 - MERCADORAMA 064 CTBA S.LOURENCO C0064","432 - MERCADORAMA 065 CTBA BACACHERI C0065","458 - MERCADORAMA 078 LONDRINA PRES.JK C0078","457 - MERCADORAMA 081 MARINGA C0081","462 - MERCADORAMA 082 UMUARAMA LONDRINA C0082",
"418 - MERCADORAMA 826 CTBA BATEL C0826","420 - MERCADORAMA 848 CTBA CABRAL C0848","68 - MERCADORAMA 868 CTBA C.CIVICO C0868","423 - MERCADORAMA 873 CTBA REBOUCAS C0873","1 - NACIONAL 001 POA P.BELAS C0011S",
"8 - NACIONAL 008 C.CANOA PARAGUACU C0008","13 - NACIONAL 013 TORRES J.BONIFACIO C0013","17 - NACIONAL 017 TRAMANDAI EMANCIPACAO C1706","302 - NACIONAL 020 POA OBIRICI","303 - NACIONAL 021 POA LINDOIA C2106",
"304 - NACIONAL 022 GRAVATAI L.BASTOS C2206","305 - NACIONAL 023 POA M.TOSTES C2306","29 - NACIONAL 029 PELOTAS L.COSTA C2906","32 - NACIONAL 032 POA M.DEUS C3206","99 - NACIONAL 033 POA L.OLIVEIRA C3306",
"37 - NACIONAL 037 POA TERESOPOLIS C3716","95 - NACIONAL 040 CAMAQUA B.GONCALV","45 - NACIONAL 045 PELOTAS G.CHAVES C0045","49 - NACIONAL 049 POA IGUATEMI C0049","50 - NACIONAL 050 PELOTAS B.AZEVEDO C0050",
"100 - NACIONAL 100 POA RUA DA PRAIA C0100","119 - NACIONAL 101 POA BELA VISTA C0101","500 - NACIONAL 101 SAPUCAIA PRIMOR","501 - NACIONAL 102 SAPUCAIA J.PEREIRA C1026","502 - NACIONAL 103 POA C.BAIXA C0103",
"503 - NACIONAL 104 ESTEIO V.OLIMPICA C0104","504 - NACIONAL 105 S.LEOPOLDO C.REI C0105","505 - NACIONAL 106 ESTEIO 24 DE AGOSTO C0106","507 - NACIONAL 108 GRAVATAI V.BRANCA C0108","508 - NACIONAL 109 VIAMAO A.VESPUCIO C0109",
"510 - NACIONAL 111 N.HAMBURGO N.SHOP","512 - NACIONAL 114 GRAVATAI D.OLIVEIRA","513 - NACIONAL 115 CANOAS G.VARGAS C0115","516 - NACIONAL 118 S.LEOPOLDO S.JOAQUIM C0188","519 - NACIONAL 121 S.MARIA MEDIANEIRA C1216",
"523 - NACIONAL 125 TAQUARA RONDA C1256","525 - NACIONAL 127 POA C.REDENTOR C1276","526 - NACIONAL 128 ALEGRETE GEN.SAMPAIO C1384","528 - NACIONAL 130 OSORIO BR 101 C1385","531 - NACIONAL 133 POA SANTANA C1386",
"533 - NACIONAL 135 N.HAMBURGO H.VELHO C0135","535 - NACIONAL 137 GUAIBA SCHELL C0137","537 - NACIONAL 139 S.GABRIEL F.ABOTT C0139","538 - NACIONAL 140 S.ANTONIO C1644","539 - NACIONAL 141 CACHOEIRINHA F.CUNHA C0141",
"541 - NACIONAL 143 POA V.AIRES C0143","542 - NACIONAL 144 C.ALTA CONCEICAO C0144","543 - NACIONAL 145 S.BORJA S.DORNELES C1456","544 - NACIONAL 146 MONTENEGRO O.ARANHA C0146","546 - NACIONAL 148 ESTEIO J.MACHADO","550 - NACIONAL 152 BAGE T.SILVEIRA C0152",
"552 - NACIONAL 154 ROSARIO C.LARGO C0154","554 - NACIONAL 156 D.PEDRITO J.CASTILHOS C0156","557 - NACIONAL 159 S.BORJA RIACHUELO","559 - NACIONAL 161 S.ANGELO F.ABREU C0161","560 - NACIONAL 162 S.MARIA A.AZEVEDO C0162",
"564 - NACIONAL 167 S.ROSA EXPEDICIONARIO C0167","568 - NACIONAL 172 POA WENCESLAU 1286 C0172","569 - NACIONAL 173 POA REPUBLICA","570 - NACIONAL 174 POA P.ALVES C0174","571 - NACIONAL 175 POA G.FREITAS C0175",
"572 - NACIONAL 176 POA JD.LEOPOLDINA C0176","574 - NACIONAL 178 B.RIBEIRO VISCONDE C0178","575 - NACIONAL 179 GUAIBA 20 SETEMBRO C0179","576 - NACIONAL 180 N.HAMBURGO G.PORTINHO C0180","578 - NACIONAL 183 IJUI J.BONIFACIO C0183",
"579 - NACIONAL 185 CANOAS J.CASTILHOS C0185","581 - NACIONAL 187 PELOTAS GEN.OSORIO C0187","582 - NACIONAL 188 R.GRANDE F.PEIXOTO C0188","584 - NACIONAL 190 S.CRUZ TEN.CEL.BRITO C0190","586 - NACIONAL 192 CAXIAS R.BRANCO",
"587 - NACIONAL 193 CAXIAS 20 DE SETEMBRO","588 - NACIONAL 194 CAXIAS S.PELEGRINO","112 - NACIONAL 197 XANGRILA CENTRO C0197","115 - NACIONAL 206 GRAMADO CENTRO C0206","118 - NACIONAL 207 IMBE C1040",
"127 - NACIONAL 215 B VISTA/POA C1049","194 - NACIONAL 219 CAXIAS DO SUL/RS","129 - NACIONAL 226 FLORIANOPOLIS C1085","139 - NACIONAL 236 BENTO GONCALVES C1108","148 - NACIONAL 267 TUBARAO",
"905 - POSTO 905 LIMEIRA","906 - POSTO 906 ARARAS C9282","907 - POSTO 907 PIRACICABA","180 - POSTO 910 CAMBORIU","181 - POSTO 912 BIG GRAVATAI","184 - POSTO 913 SUPERCENTER BAURU/SP","271 - POSTO 915 LINHA AMARELA RJ",
"182 - POSTO 918 SAMS NITEROI/RJ","185 - POSTO 929 SAO BERNARDO DO CAMPO/SP","179 - POSTO 939 MAXXI SANTA MARIA","261 - POSTO 940 CONTAGEM","273 - POSTO 941 HTD PAULISTA PE","239 - POSTO 944 NOVO HAMBURGO/RS",
"272 - POSTO 947 CAMPO MOURAO","4953 - SAMS AGUAS CLARAS","4857 - SAMS BARIGUI","4825 - SAMS BOM RETIRO","4935 - SAMS BRASILIA","4938 - SAMS CAMPINAS","6278 - SAMS CONTAGEM","6230 - SAMS CURITIBA",
"4944 - SAMS FORTALEZA","4934 - SAMS GOIANIA","4940 - SAMS GUARULHOS","4937 - SAMS MACEIO","4943 - SAMS NATAL","6268 - SAMS NITEROI","6546 - SAMS OSASCO","4918 - SAMS RADIAL","4941 - SAMS RECIFE",
"4949 - SAMS RIBEIRAO PRETO","6277 - SAMS RJ","6466 - SAMS S C SUL","4931 - SAMS S J CAMPOS","4936 - SAMS SALVADOR","4951 - SAMS SAO BERNARDO DO CAMPO","4947 - SAMS SERTORIO","6266 - SAMS STO AMARO",
"6532 - SAMS STO ANDRE","4932 - SAMS TAMBORE","4933 - SAMS VITORIA","308 - SUPER TODO DIA ITAPECURU MIRIM","1133 - SUPERC AGUAS CLARAS","199 - SUPERC AMERICANA","151 - SUPERC ARARAS","3708 - SUPERC ARICANDUVA",
"5724 - SUPERC ARTHUR BERNARDES","1540 - SUPERC ASSIS","3702 - SUPERC BAURU","1009 - SUPERC BRASILIA","1275 - SUPERC BRASILIA ASA NORTE","1257 - SUPERC C.GRANDE BOSQUE IPES","5837 - SUPERC CABRAL","89 - SUPERC CAMPINAS OUT LET",
"87 - SUPERC CAMPINAS SHOPPING DOM P","1018 - SUPERC CAMPO GRANDE","1039 - SUPERC CAMPOS DOS GOYTACAZES","1554 - SUPERC CATANDUVA","3704 - SUPERC CENTRAL PLAZA","3710 - SUPERC CONTAGEM","1023 - SUPERC COTIA","3706 - SUPERC CURITIBA",
"1022 - SUPERC FRANCA","1008 - SUPERC GOIANIA","1033 - SUPERC GOIANIA NORTE","1029 - SUPERC GUARULHOS","1416 - SUPERC HORTOLANDIA","1001 - SUPERC INDIANOPOLIS","1307 - SUPERC ITU","99 - SUPERC LIMEIRA",
"1116 - SUPERC LONDRINA","1200 - SUPERC MACAE","1281 - SUPERC MARILIA","113 - SUPERC MOGI GUACU","1019 - SUPERC MORUMBI","2801 - SUPERC OSASCO","3705 - SUPERC PACAEMBU","1274 - SUPERC PAMPULHA",
"1520 - SUPERC PASSOS","1519 - SUPERC PATOS DE MINAS","1666 - SUPERC PIRACICABA","1308 - SUPERC PRESIDENTE PRUDENTE","3703 - SUPERC RIB PRETO","3712 - SUPERC RIO DE JANEIRO","3700 - SUPERC S B CAMPO","3707 - SUPERC S J CAMPOS",
"1017 - SUPERC SAO JOSE DO RIO PRETO","1016 - SUPERC SOROCABA","2800 - SUPERC STO ANDRE","1509 - SUPERC SUMARE","1005 - SUPERC TAMBORE","1047 - SUPERC UBERABA","1146 - SUPERC UBERLANDIA","1007 - SUPERC VILA GUILHERME",
"1025 - SUPERC VILA LEOPOLDINA","1006 - SUPERC VITORIA","1478 - SUPERC VOLTA REDONDA","1004 - SUPERC WASHINGTON LUIS","1417 - SUPERCENTER JACAREI","520 - TODO DIA 122 CANOAS G.SCHELL 7500 C1226","156 - TODO DIA 278 PROTASIO ALVES C1283",
"151 - TODO DIA 279 CAMPO BOM C1272","174 - TODO DIA 287 PINHAIS/PR C1444","169 - TODO DIA 288 CANUDOS II C1291","186 - TODO DIA 290 ESTANCIA VELHA CANOAS C1319","173 - TODO DIA 293 TAQUARA/RS C1318","175 - TODO DIA 296 IGREJINHA/RS C1311",
"187 - TODO DIA 297 ALTO BOQUEIRAO/PR C1310","190 - TODO DIA 300 CANUDOS I C1320","191 - TODO DIA 304 ALVORADA C1336","195 - TODO DIA 306 LAPA/PR C1340","228 - TODO DIA 314 SAO LEOPOLDO RS C1354","196 - TODO DIA 317 PARANAGUA/PR C1353",
"197 - TODO DIA 326 RIO PARDO C1376","237 - TODO DIA 327 PARANAGUA B MUNHOZ C1390","236 - TODO DIA 329 ARAUCARIA/ PR C1370","249 - TODO DIA 331 SAO LEOPOLDO CAMPINA C1441","226 - TODO DIA 332 SAPUCAIA DO SUL RS C1378","227 - TODO DIA 333 PAROBE RS C1375","242 - TODO DIA 343 ERNESTO VILELA C1392",
"235 - TODO DIA 345 PONTA GROSSA/PR C1410","241 - TODO DIA 346 SAO JOSE DOS PINHAIS C1414","313 - TODO DIA 351 PARANAGUAMIRIM C1423","243 - TODO DIA 352 PIRAQUARA C1440","310 - TODO DIA 353 IRIRIU C1437","246 - TODO DIA 355 COSTA E SILVA SC C1443","247 - TODO DIA 356 E.PERNETA PINHAIS C1301","253 - TODO DIA 357 CANOAS RIO BRANCO C1445",
"244 - TODO DIA 358 VIAMAO C1459","245 - TODO DIA 360 SAO MATEUS DO SUL C1461","248 - TODO DIA 362 COMASA JOINVILLE SC C1458","254 - TODO DIA 376 PASQUALINI SAP DO SUL C1487","311 - TODO DIA 379 BOEHMERWALD JOINVILLE C1485","258 - TODO DIA 381 CASTRO PR C1491","1123 - TODO DIA ACHIOLE","1243 - TODO DIA ALTO DE ITAQUAQUECETU",
"1371 - TODO DIA CAMPOS ELISEOS","1138 - TODO DIA CARAPICUIBA -VILA CRE","1161 - TODO DIA CARAPICUIBA BETSAIDA","1139 - TODO DIA CARAPICUIBA GOPIUVA","1125 - TODO DIA DIADEMA CAMPANARIO","1175 - TODO DIA DIADEMA VILA NOGUEIRA",
"306 - TODO DIA EUSTAQUIO GOMES","1271 - TODO DIA GUARULHOS - WALTER RI","1435 - TODO DIA INDEPENDENCIA","1377 - TODO DIA JARDIM BRASILIA","1182 - TODO DIA JD SAO LUIS","1261 - TODO DIA MOGI DAS CRUZES MOGIL",
"1159 - TODO DIA OSASCO AYROSA","1372 - TODO DIA OURO VERDE","1329 - TODO DIA PALMEIRAS","1246 - TODO DIA ROSEIRA PARK CARAPICU","1166 - TODO DIA SANTO ANDRE- PALMARES","1158 - TODO DIA SAO MATEUS","1230 - TODO DIA SAO PAULO JD JORDANIA","1207 - TODO DIA SAO PAULO NORDESTINA","1317 - TODO DIA SAO VICENTE - MARGARI","1126 - TODO DIA SERRARIA","1413 - TODO DIA SETE LAGOAS","887 - TRANSPORTADORA - BAHIA","883 - TRANSPORTADORA - BARUERI -SP","889 - TRANSPORTADORA - BETIM","890 - TRANSPORTADORA - MARANHAO","7485 - TRANSPORTADORA - PINHAIS","7486 - TRANSPORTADORA - POA","888 - TRANSPORTADORA BOMPRECO LTDA","8771 - WMB COMERCIO ELETRONICO"
	];
	$("#help_friend" ).autocomplete({
		source: esportes
	});

        $("#form").submit(function () {
            return false;
        });
        $("#envia").click(function () {
            envia_form();
        });
        function envia_form() {
            $("#conteudo_periodico").empty();
            var empresa = $("#empresa").val();
            var estabelecimento = $("#estabelecimento").val();

            if ($("#empresa").val() === '0') {
                $("#empresa_error").html("<div class='alert alert-danger alert-dismissable'><button type='button' class='close' data-dismiss='alert' aria-hidden='true'>×</button>Informe Empresa...</div>").hide(2405),
                        $("#empresa").focus();
                return false;
            } else {
                $("#empresa_error").empty();
            }

            if ($("#estabelecimento").val() === '0' || $("#estabelecimento").val() === 'na') {
                $("#estabelecimento_error").html("<div class='alert alert-danger alert-dismissable'><button type='button' class='close' data-dismiss='alert' aria-hidden='true'>×</button>Informe Loja...</div>").hide(2407),
                        $("#estabelecimento").focus();
                return false;
            } else {
                $("#estabelecimento_error").empty();
            }

            $.ajax({
                type: "POST",
                dataType: "HTML",
                url: "../Controller/wal_listar2016.php",
                data: "empresa=" + empresa + "&estabelecimento=" + estabelecimento,
                beforeSend: function () {
                    $("#conteudo_periodico").html("<img src='../../images/loading/load.gif' class='img-rounded img-responsive' id='imgpos'>");
                },
                success: function (response) {
                    $("#conteudo_periodico").html(response),
                            $('#button').css("display", "block").show(1090),
                            $('#datadoperiodico').css("display", "block").show(1090);
                },
                error: function () {
                    alert("Ocorreu um erro durante a requisição");
                }
            });
        }
    });
</script>
<script>
    $(document).ready(function () {
        $("#button").click(function () {
            envia_array();
        });
        function envia_array() {
            var favorite = [];
            $.each($("input[name='matricula']:checked"), function () {
                favorite.push($(this).val());
            });
            var errou = [];
            $.each($("input[name='erro']:checked"), function () {
                errou.push($(this).val());
            });

            var erro_identificacao = [];
            $.each($("input[name='erro_identificacao']:checked"), function () {
                erro_identificacao.push($(this).val());
            });

            var erro_riscos = [];
            $.each($("input[name='erro_riscos']:checked"), function () {
                erro_riscos.push($(this).val());
            });

            var erro_data_ASO = [];
            $.each($("input[name='erro_data_ASO']:checked"), function () {
                erro_data_ASO.push($(this).val());
            });

            var erro_data_exames = [];
            $.each($("input[name='erro_data_exames']:checked"), function () {
                erro_data_exames.push($(this).val());
            });

            var erro_assinatura_ativo = [];
            $.each($("input[name='erro_assinatura_ativo']:checked"), function () {
                erro_assinatura_ativo.push($(this).val());
            });

            var erro_assinatura_medico = [];
            $.each($("input[name='erro_assinatura_medico']:checked"), function () {
                erro_assinatura_medico.push($(this).val());
            });

            var erro_carimbo = [];
            $.each($("input[name='erro_carimbo']:checked"), function () {
                erro_carimbo.push($(this).val());
            });

            var erro_rasuras = [];
            $.each($("input[name='erro_rasuras']:checked"), function () {
                erro_rasuras.push($(this).val());
            });

            var erro_falta_apto = [];
            $.each($("input[name='erro_falta_apto']:checked"), function () {
                erro_falta_apto.push($(this).val());
            });

            var erro_falta_habilitado = [];
            $.each($("input[name='erro_falta_habilitado']:checked"), function () {
                erro_falta_habilitado.push($(this).val());
            });
            
            var erro_tel = [];
            $.each($("input[name='erro_tel']:checked"), function () {
                erro_tel.push($(this).val());
            });
            
            var erro_coord = [];
            $.each($("input[name='erro_coord']:checked"), function () {
                erro_coord.push($(this).val());
            });
            
            var erro_duplicado = [];
            $.each($("input[name='erro_duplicado']:checked"), function () {
                erro_duplicado.push($(this).val());
            });
            
            var falta_aso = [];
            $.each($("input[name='falta_aso']:checked"), function () {
                falta_aso.push($(this).val());
            });

            var data_periodico = $("#data_periodico").val();
            var id_medico = $("#id_medico").val();
            var id_medico_coordenador = $("#id_medico_coordenador").val();
            var caixa = $("#caixa").val();
            var comp_ACIDO_METIL_HIPURICO = $("#comp_ACIDO_METIL_HIPURICO").val() === '' ? '0000-00-00 00:00:00' : $("#comp_ACIDO_METIL_HIPURICO").val();
            var comp_HEMOGRAMA = $("#comp_HEMOGRAMA").val() === '' ? '0000-00-00 00:00:00' : $("#comp_HEMOGRAMA").val();
            var comp_ACIDO_MANDELICO = $("#comp_ACIDO_MANDELICO").val() === '' ? '0000-00-00 00:00:00' : $("#comp_ACIDO_MANDELICO").val();
            var comp_VDRL = $("#comp_VDRL").val() === '' ? '0000-00-00 00:00:00' : $("#comp_VDRL").val();
            var comp_RETICULOCITOS = $("#comp_RETICULOCITOS").val() === '' ? '0000-00-00 00:00:00' : $("#comp_RETICULOCITOS").val();
            var comp_PARASITOLOGICO_FEZES = $("#comp_PARASITOLOGICO_FEZES").val() === '' ? '0000-00-00 00:00:00' : $("#comp_PARASITOLOGICO_FEZES").val();
            var comp_CULTURAL_DE_OROFARINGE = $("#comp_CULTURAL_DE_OROFARINGE").val() === '' ? '0000-00-00 00:00:00' : $("#comp_CULTURAL_DE_OROFARINGE").val();
            var comp_COPROCULTURA = $("#comp_COPROCULTURA").val() === '' ? '0000-00-00 00:00:00' : $("#comp_COPROCULTURA").val();
            var comp_MICOLOGICO_DE_UNHA = $("#comp_MICOLOGICO_DE_UNHA").val() === '' ? '0000-00-00 00:00:00' : $("#comp_MICOLOGICO_DE_UNHA").val();
            var comp_AUDIOMETRIA = $("#comp_AUDIOMETRIA").val() === '' ? '0000-00-00 00:00:00' : $("#comp_AUDIOMETRIA").val();
            var comp_ECG = $("#comp_ECG").val() === '' ? '0000-00-00 00:00:00' : $("#comp_ECG").val();
            var comp_ACUIDADE_VISUAL = $("#comp_ACUIDADE_VISUAL").val() === '' ? '0000-00-00 00:00:00' : $("#comp_ACUIDADE_VISUAL").val();
            var comp_EEG = $("#comp_EEG").val() === '' ? '0000-00-00 00:00:00' : $("#comp_EEG").val();
            var comp_PLAQUETAS = $("#comp_PLAQUETAS").val() === '' ? '0000-00-00 00:00:00' : $("#comp_PLAQUETAS").val();
            var comp_ERITROGRAMA = $("#comp_ERITROGRAMA").val() === '' ? '0000-00-00 00:00:00' : $("#comp_ERITROGRAMA").val();
            var comp_ACIDO_TT_MUCONICO = $("#comp_ACIDO_TT_MUCONICO").val() === '' ? '0000-00-00 00:00:00' : $("#comp_ACIDO_TT_MUCONICO").val();
            var comp_GLICEMIA_EM_JEJUM = $("#comp_GLICEMIA_EM_JEJUM").val() === '' ? '0000-00-00 00:00:00' : $("#comp_GLICEMIA_EM_JEJUM").val();
            var comp_ACIDO_HIPURICO = $("#comp_ACIDO_HIPURICO").val() === '' ? '0000-00-00 00:00:00' : $("#comp_ACIDO_HIPURICO").val();
            var comp_AVALIACAO_PSICOSSOCIAL = $("#comp_AVALIACAO_PSICOSSOCIAL").val() === '' ? '0000-00-00 00:00:00' : $("#comp_AVALIACAO_PSICOSSOCIAL").val();            
            var comp_anti_Hbs = $("#comp_anti_Hbs").val() === '' ? '0000-00-00 00:00:00' : $("#comp_anti_Hbs").val();
            var comp_HBs_Ag = $("#comp_HBs_Ag").val() === '' ? '0000-00-00 00:00:00' : $("#comp_HBs_Ag").val();
            var comp_Anti_HBc = $("#comp_Anti_HBc").val() === '' ? '0000-00-00 00:00:00' : $("#comp_Anti_HBc").val();            
            var status_ACIDO_METIL_HIPURICO = $("#status_ACIDO_METIL_HIPURICO").val() === 'na' ? 0 : $("#status_ACIDO_METIL_HIPURICO").val();
            var status_HEMOGRAMA = $("#status_HEMOGRAMA").val() === 'na' ? 0 : $("#status_HEMOGRAMA").val();
            var status_ACIDO_MANDELICO = $("#status_ACIDO_MANDELICO").val() === 'na' ? 0 : $("#status_ACIDO_MANDELICO").val();
            var status_VDRL = $("#status_VDRL").val() === 'na' ? 0 : $("#status_VDRL").val();
            var status_RETICULOCITOS = $("#status_RETICULOCITOS").val() === 'na' ? 0 : $("#status_RETICULOCITOS").val();
            var status_PARASITOLOGICO_FEZES = $("#status_PARASITOLOGICO_FEZES").val() === 'na' ? 0 : $("#status_PARASITOLOGICO_FEZES").val();
            var status_CULTURAL_DE_OROFARINGE = $("#status_CULTURAL_DE_OROFARINGE").val() === 'na' ? 0 : $("#status_CULTURAL_DE_OROFARINGE").val();
            var status_COPROCULTURA = $("#status_COPROCULTURA").val() === 'na' ? 0 : $("#status_COPROCULTURA").val();
            var status_MICOLOGICO_DE_UNHA = $("#status_MICOLOGICO_DE_UNHA").val() === 'na' ? 0 : $("#status_MICOLOGICO_DE_UNHA").val();
            var status_AUDIOMETRIA = $("#status_AUDIOMETRIA").val() === 'na' ? 0 : $("#status_AUDIOMETRIA").val();
            var status_ECG = $("#status_ECG").val() === 'na' ? 0 : $("#status_ECG").val();
            var status_ACUIDADE_VISUAL = $("#status_ACUIDADE_VISUAL").val() === 'na' ? 0 : $("#status_ACUIDADE_VISUAL").val();
            var status_EEG = $("#status_EEG").val() === 'na' ? 0 : $("#status_EEG").val();
            var status_PLAQUETAS = $("#status_PLAQUETAS").val() === 'na' ? 0 : $("#status_PLAQUETAS").val();
            var status_ERITROGRAMA = $("#status_ERITROGRAMA").val() === 'na' ? 0 : $("#status_ERITROGRAMA").val();
            var status_ACIDO_TT_MUCONICO = $("#status_ACIDO_TT_MUCONICO").val() === 'na' ? 0 : $("#status_ACIDO_TT_MUCONICO").val();
            var status_GLICEMIA_EM_JEJUM = $("#status_GLICEMIA_EM_JEJUM").val() === 'na' ? 0 : $("#status_GLICEMIA_EM_JEJUM").val();
            var status_ACIDO_HIPURICO = $("#status_ACIDO_HIPURICO").val() === 'na' ? 0 : $("#status_ACIDO_HIPURICO").val();
            var status_AVALIACAO_PSICOSSOCIAL = $("#status_AVALIACAO_PSICOSSOCIAL").val() === 'na' ? 0 : $("#status_AVALIACAO_PSICOSSOCIAL").val();            
            var status_anti_Hbs = $("#status_anti_Hbs").val() === 'na' ? 0 : $("#status_anti_Hbs").val();
            var status_HBs_Ag = $("#status_HBs_Ag").val() === 'na' ? 0 : $("#status_HBs_Ag").val();
            var status_Anti_HBc = $("#status_Anti_HBc").val() === 'na' ? 0 : $("#status_Anti_HBc").val();
            
            if ($("#data_periodico").val() === 'na') {
                $("#caixa_error").html("<div class='alert alert-danger alert-dismissable'><button type='button' class='close' data-dismiss='alert' aria-hidden='true'>×</button>Informe...</div>"),
                        $("#data_periodico").focus();
                return false;
            } else {
                $("#caixa_error").empty();
            }

            if ($("#caixa").val() === 'na') {
                $("#caixa_error").html("<div class='alert alert-danger alert-dismissable'><button type='button' class='close' data-dismiss='alert' aria-hidden='true'>×</button>Informe...</div>"),
                        $("#caixa").focus();
                return false;
            } else {
                $("#caixa_error").empty();
            }
            
            if ($("#id_medico").val() === 'na') {
                $("#caixa_error").html("<div class='alert alert-danger alert-dismissable'><button type='button' class='close' data-dismiss='alert' aria-hidden='true'>×</button>Informe...</div>"),
                        $("#id_medico").focus();
                return false;
            } else {
                $("#caixa_error").empty();
            }
            
            if ($("#id_medico_coordenador").val() === 'na') {
                $("#caixa_error").html("<div class='alert alert-danger alert-dismissable'><button type='button' class='close' data-dismiss='alert' aria-hidden='true'>×</button>Informe...</div>"),
                        $("#id_medico_coordenador").focus();
                return false;
            } else {
                $("#caixa_error").empty();
            }

            $.ajax({
                type: "GET",
                dataType: "HTML",
                url: "../Controller/periodico_realizados2016.php",
                data: "periodico=" + favorite + "&data_periodico=" + data_periodico + "&erro=" + errou +
                        "&comp_ACIDO_METIL_HIPURICO=" + comp_ACIDO_METIL_HIPURICO + "&comp_HEMOGRAMA=" + comp_HEMOGRAMA
                        + "&comp_ACIDO_MANDELICO=" + comp_ACIDO_MANDELICO + "&comp_VDRL=" + comp_VDRL + "&comp_RETICULOCITOS="
                        + comp_RETICULOCITOS + "&comp_PARASITOLOGICO_FEZES=" + comp_PARASITOLOGICO_FEZES + "&comp_CULTURAL_DE_OROFARINGE="
                        + comp_CULTURAL_DE_OROFARINGE + "&comp_COPROCULTURA=" + comp_COPROCULTURA
                        + "&comp_MICOLOGICO_DE_UNHA=" + comp_MICOLOGICO_DE_UNHA + "&comp_AUDIOMETRIA=" + comp_AUDIOMETRIA +
                        "&comp_ECG=" + comp_ECG + "&comp_ACUIDADE_VISUAL=" + comp_ACUIDADE_VISUAL + "&comp_EEG=" + comp_EEG +
                        "&comp_PLAQUETAS=" + comp_PLAQUETAS + "&comp_ERITROGRAMA=" + comp_ERITROGRAMA
                        + "&comp_ACIDO_TT_MUCONICO=" + comp_ACIDO_TT_MUCONICO + "&comp_GLICEMIA_EM_JEJUM=" + comp_GLICEMIA_EM_JEJUM +
                        "&comp_ACIDO_HIPURICO=" + comp_ACIDO_HIPURICO + "&comp_AVALIACAO_PSICOSSOCIAL=" + comp_AVALIACAO_PSICOSSOCIAL + "&caixa=" + caixa +
                        "&status_ACIDO_METIL_HIPURICO=" + status_ACIDO_METIL_HIPURICO + "&status_HEMOGRAMA=" + status_HEMOGRAMA + "&status_ACIDO_MANDELICO=" + status_ACIDO_MANDELICO + "&status_VDRL=" + status_VDRL + "&status_RETICULOCITOS=" + status_RETICULOCITOS + "&status_PARASITOLOGICO_FEZES=" + status_PARASITOLOGICO_FEZES +
                        "&status_CULTURAL_DE_OROFARINGE=" + status_CULTURAL_DE_OROFARINGE + "&status_COPROCULTURA=" + status_COPROCULTURA + "&status_MICOLOGICO_DE_UNHA=" + status_MICOLOGICO_DE_UNHA +
                        "&status_AUDIOMETRIA=" + status_AUDIOMETRIA + "&status_ECG=" + status_ECG + "&status_ACUIDADE_VISUAL=" + status_ACUIDADE_VISUAL +
                        "&status_EEG=" + status_EEG + "&status_PLAQUETAS=" + status_PLAQUETAS + "&status_ERITROGRAMA=" + status_ERITROGRAMA +
                        "&status_ACIDO_TT_MUCONICO=" + status_ACIDO_TT_MUCONICO + "&status_GLICEMIA_EM_JEJUM=" + status_GLICEMIA_EM_JEJUM +
                        "&status_ACIDO_HIPURICO=" + status_ACIDO_HIPURICO + "&status_AVALIACAO_PSICOSSOCIAL=" + status_AVALIACAO_PSICOSSOCIAL +
                        "&erro_identificacao=" + erro_identificacao + "&erro_riscos=" + erro_riscos +
                        "&erro_data_ASO=" + erro_data_ASO + "&erro_data_exames=" + erro_data_exames +
                        "&erro_assinatura_ativo=" + erro_assinatura_ativo + "&erro_assinatura_medico=" + erro_assinatura_medico +
                        "&erro_carimbo=" + erro_carimbo + "&erro_rasuras=" + erro_rasuras +
                        "&erro_falta_apto=" + erro_falta_apto + "&erro_falta_habilitado=" + erro_falta_habilitado + "&id_medico=" + id_medico + "&id_medico_coordenador=" + id_medico_coordenador + 
                        "&erro_tel=" + erro_tel + "&erro_coord=" + erro_coord + "&erro_duplicado=" + erro_duplicado + "&falta_aso=" + falta_aso + 
                        "&comp_anti_Hbs=" + comp_anti_Hbs + "&status_anti_Hbs=" + status_anti_Hbs + "&comp_HBs_Ag=" + comp_HBs_Ag + 
                        "&status_HBs_Ag=" + status_HBs_Ag + "&comp_Anti_HBc=" + comp_Anti_HBc + "&status_Anti_HBc=" + status_Anti_HBc,
                beforeSend: function () {
                    $("#periodico").html("<img src='../../images/loading/load.gif' class='img-rounded img-responsive'>");
                },
                success: function (response) {
                    $("#periodico").html(response),
                    $("#data_periodico").val(''),
                            $("#caixa").val(''),
                            $("#comp_ACIDO_METIL_HIPURICO").val(''),
                            $("#comp_HEMOGRAMA").val(''),
                            $("#comp_ACIDO_MANDELICO").val(''),
                            $("#comp_VDRL").val(''),
                            $("#comp_RETICULOCITOS").val(''),
                            $("#comp_PARASITOLOGICO_FEZES").val(''),
                            $("#comp_CULTURAL_DE_OROFARINGE").val(''),
                            $("#comp_COPROCULTURA").val(''),
                            $("#comp_MICOLOGICO_DE_UNHA").val(''),
                            $("#comp_AUDIOMETRIA").val(''),
                            $("#comp_ECG").val(''),
                            $("#comp_ACUIDADE_VISUAL").val(''),
                            $("#comp_EEG").val(''),
                            $("#comp_PLAQUETAS").val(''),
                            $("#comp_ERITROGRAMA").val(''),
                            $("#comp_ACIDO_TT_MUCONICO").val(''),
                            $("#comp_GLICEMIA_EM_JEJUM").val(''),
                            $("#comp_ACIDO_HIPURICO").val(''),
                            $("#comp_AVALIACAO_PSICOSSOCIAL").val(''),                            
                            $("#status_ACIDO_METIL_HIPURICO").val('na'),
                            $("#status_HEMOGRAMA").val('na'),
                            $("#status_ACIDO_MANDELICO").val('na'),
                            $("#status_VDRL").val('na'),
                            $("#status_RETICULOCITOS").val('na'),
                            $("#status_PARASITOLOGICO_FEZES").val('na'),
                            $("#status_CULTURAL_DE_OROFARINGE").val('na'),
                            $("#status_COPROCULTURA").val('na'),
                            $("#status_MICOLOGICO_DE_UNHA").val('na'),
                            $("#status_AUDIOMETRIA").val('na'),
                            $("#status_ECG").val('na'),
                            $("#status_ACUIDADE_VISUAL").val('na'),
                            $("#status_EEG").val('na'),
                            $("#status_PLAQUETAS").val('na'),
                            $("#status_ERITROGRAMA").val('na'),
                            $("#status_ACIDO_TT_MUCONICO").val('na'),
                            $("#status_GLICEMIA_EM_JEJUM").val('na'),
                            $("#status_ACIDO_HIPURICO").val('na'),
                            $("#status_AVALIACAO_PSICOSSOCIAL").val('na'),                    
                            $("#comp_anti_Hbs").val(''),
                            $("#status_anti_Hbs").val('na'),
                            $("#comp_HBs_Ag").val(''),
                            $("#status_HBs_Ag").val('na'),
                            $("#comp_Anti_HBc").val(''),
                            $("#status_HBs_Ag").val('na');
                },
                error: function () {
                    alert("Ocorreu um erro durante a requisição");
                }
            });
        }
    });
</script>
<style type="text/css">
    #imgpos {
        position:absolute;
        left:667px;
    }
</style>
<div class="widget">
    <div class="widget-header transparent">
        <h2><strong>Listar Funcionários</strong> <acronym title="Informe os campos para otimizar o resultado!!!">Walmart</acronym></h2>
        <div class="additional-btn">            
            <a href="#" class="widget-toggle"><i class="icon-down-open-2"></i></a>            
        </div>
    </div>
    <div class="widget-content padding">
        <div class="form-inline">
            <form id="form" method="POST">
                <div class="form-group">
                    <label for="empresa_label">Ajuda:</label>
                    <input class="form-control" id="help_friend" name="help_friend">
                </div>
                <div class="form-group">
                    <label for="empresa_label">Empresa:</label>
                    <select class="form-control" id="empresa" name="empresa" required autofocus>
                        <option selected value="0">
                            Selecione...
                        </option>
                        <?php
                        include '../config/database_mysql.php';
                        $pdo = Database::connect();
                        $sql = "SELECT cod_empresa, concat(cod_empresa,' - ',desc_empresa) as desc_empresas FROM wal_empresa_2016 ORDER BY desc_empresa ASC";
                        foreach ($pdo->query($sql) as $value) {
                            echo '<option value="' . $value['cod_empresa'] . '">' . $value['desc_empresas'] . '</option>';
                        }
                        ?>
                    </select>
                    <div class="form-inline" id="empresa_error"></div>
                </div>
                <div class="form-group">
                    <label for="estabelecimento_label">Estabelecimento:</label>
                    <select class="form-control" id="estabelecimento" name="estabelecimento" required>
                        <option selected value="na">
                            Aguardando...
                        </option>
                    </select>
                    <div class="form-inline" id="estabelecimento_error"></div>
                </div>
                <button class="btn btn-primary" id="envia" type="submit">Gerar Lista de Ativos</button>                
            </form>
        </div>
    </div>    
    <div class="widget-content padding" id="conteudo_periodico"></div>
    <div class="widget-content padding">
        <div id="datadoperiodico">
            <div class="form-group">
                <label for="estabelecimento_label">Data do Exame Clínico:</label>
                <input type="date" class="form-inline" id="data_periodico" name="data_periodico">
                <label for="estabelecimento_label">Caixa:</label>                        
                <select class="form-inline" id="caixa" name="caixa" required>
                    <option selected value="na">
                        Selecione...
                    </option>
                    <?php
                    $sql1 = "select id, etiqueta from wal_caixa where id_wal_box in (1) and status in (1) order by etiqueta asc";
                    foreach ($pdo->query($sql1) as $value) {
                        echo '<option value="' . $value['id'] . '">' . $value['etiqueta'] . '</option>';
                    }
                    ?>
                </select>
                <div class="form-group">
                    <label for="estabelecimento_label">Médico:</label>                        
                    <select class="form-inline" id="id_medico" name="id_medico" required>
                        <option selected value="na">
                            Selecione...
                        </option>
                        <?php
                        $sqlmedico = "select id, nome_extenso from usuarios where setor in (28) and status in (1) order by nome asc";
                        foreach ($pdo->query($sqlmedico) as $value) {
                            echo '<option value="' . $value['id'] . '">' . $value['nome_extenso'] . '</option>';
                        }
                        ?>
                    </select>
                </div>
                <div class="form-group">
                    <label for="estabelecimento_label">Médico Coordenador:</label>                        
                    <select class="form-inline" id="id_medico_coordenador" name="id_medico_coordenador" required>
                        <option selected value="na">
                            Selecione...
                        </option>
                        <?php
                        $sqlmedico_coord = "select id, nome from pcmso_coordenadores where ativo in (1) order by nome asc";
                        foreach ($pdo->query($sqlmedico_coord) as $value) {
                            echo '<option value="' . $value['id'] . '">' . utf8_encode($value['nome']) . '</option>';
                        }
                        ?>
                    </select>
                </div>
                <div class="form-inline" id="caixa_error"></div>                
            </div>            
            <div class="form-group">
                <table class="table table-striped table-bordered">
                    <tr>
                        <td colspan="3" class="text-center text-uppercase"><strong>complementares</strong></td>
                    </tr>
                    <tr>
                        <td class="text-center">ÁCIDO METIL-HIPÚRICO</td>
                        <td class="text-center">HEMOGRAMA</td>
                        <td class="text-center">ÁCIDO MANDÉLICO</td>
                    </tr>
                    <tr>
                        <td class="text-center">
                            <input type="date" id="comp_ACIDO_METIL_HIPURICO" name="comp_ACIDO_METIL_HIPURICO"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_ACIDO_METIL_HIPURICO" name="status_ACIDO_METIL_HIPURICO" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql2 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql2) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                        <td class="text-center">
                            <input type="date" id="comp_HEMOGRAMA" name="comp_HEMOGRAMA"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_HEMOGRAMA" name="status_HEMOGRAMA" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql3 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql3) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                        <td class="text-center">
                            <input type="date" id="comp_ACIDO_MANDELICO" name="comp_ACIDO_MANDELICO"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_ACIDO_MANDELICO" name="status_ACIDO_MANDELICO" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql4 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql4) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">VDRL</td>
                        <td class="text-center">RETICULÓCITOS</td>
                        <td class="text-center">PARASITOLÓGICO FEZES</td>
                    </tr>
                    <tr>
                        <td class="text-center"><input type="date" id="comp_VDRL" name="comp_VDRL"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_VDRL" name="status_VDRL" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql5 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql5) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                        <td class="text-center"><input type="date" id="comp_RETICULOCITOS" name="comp_RETICULOCITOS"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_RETICULOCITOS" name="status_RETICULOCITOS" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql6 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql6) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                        <td class="text-center"><input type="date" id="comp_PARASITOLOGICO_FEZES" name="comp_PARASITOLOGICO_FEZES"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_PARASITOLOGICO_FEZES" name="status_PARASITOLOGICO_FEZES" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql7 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql7) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">CULTURAL DE OROFARINGE</td>
                        <td class="text-center">COPROCULTURA</td>
                        <td class="text-center">MICOLÓGICO DE UNHA</td>
                    </tr>
                    <tr>
                        <td class="text-center"><input type="date" id="comp_CULTURAL_DE_OROFARINGE" name="comp_CULTURAL_DE_OROFARINGE"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_CULTURAL_DE_OROFARINGE" name="status_CULTURAL_DE_OROFARINGE" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql8 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql8) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                        <td class="text-center"><input type="date" id="comp_COPROCULTURA" name="comp_COPROCULTURA"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_COPROCULTURA" name="status_COPROCULTURA" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql9 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql9) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                        <td class="text-center"><input type="date" id="comp_MICOLOGICO_DE_UNHA" name="comp_MICOLOGICO_DE_UNHA"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_MICOLOGICO_DE_UNHA" name="status_MICOLOGICO_DE_UNHA" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql10 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql10) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">AUDIOMETRIA</td>
                        <td class="text-center">ECG</td>
                        <td class="text-center">ACUIDADE VISUAL</td>
                    </tr>
                    <tr>
                        <td class="text-center"><input type="date" id="comp_AUDIOMETRIA" name="comp_AUDIOMETRIA"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_AUDIOMETRIA" name="status_AUDIOMETRIA" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql11 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql11) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                        <td class="text-center"><input type="date" id="comp_ECG" name="comp_ECG"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_ECG" name="status_ECG" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql12 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql12) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                        <td class="text-center"><input type="date" id="comp_ACUIDADE_VISUAL" name="comp_ACUIDADE_VISUAL"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_ACUIDADE_VISUAL" name="status_ACUIDADE_VISUAL" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql13 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql13) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">EEG</td>
                        <td class="text-center">PLAQUETAS</td>
                        <td class="text-center">ERITROGRAMA</td>
                    </tr>
                    <tr>
                        <td class="text-center"><input type="date" id="comp_EEG" name="comp_EEG"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_EEG" name="status_EEG" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql14 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql14) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                        <td class="text-center"><input type="date" id="comp_PLAQUETAS" name="comp_PLAQUETAS"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_PLAQUETAS" name="status_PLAQUETAS" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql15 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql15) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                        <td class="text-center"><input type="date" id="comp_ERITROGRAMA" name="comp_ERITROGRAMA"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_ERITROGRAMA" name="status_ERITROGRAMA" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql16 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql16) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">ÁCIDO TT MUCÔNICO</td>
                        <td class="text-center">GLICEMIA EM JEJUM</td>
                        <td class="text-center">ÁCIDO HIPÚRICO</td>
                    </tr>
                    <tr>
                        <td class="text-center"><input type="date" id="comp_ACIDO_TT_MUCONICO" name="comp_ACIDO_TT_MUCONICO"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_ACIDO_TT_MUCONICO" name="status_ACIDO_TT_MUCONICO" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql17 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql17) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                        <td class="text-center"><input type="date" id="comp_GLICEMIA_EM_JEJUM" name="comp_GLICEMIA_EM_JEJUM"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_GLICEMIA_EM_JEJUM" name="status_GLICEMIA_EM_JEJUM" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql18 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql18) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?></td>
                        <td class="text-center"><input type="date" id="comp_ACIDO_HIPURICO" name="comp_ACIDO_HIPURICO"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_ACIDO_HIPURICO" name="status_ACIDO_HIPURICO" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql19 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql19) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">AVALIAÇÃO PSICOSSOCIAL</td>
                        <td class="text-center">Anti-HBs</td>
                        <td class="text-center">HBs-Ag</td>
                    </tr>
                    <tr>
                        <td class="text-center"><input type="date" id="comp_AVALIACAO_PSICOSSOCIAL" name="comp_AVALIACAO_PSICOSSOCIAL"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_AVALIACAO_PSICOSSOCIAL" name="status_AVALIACAO_PSICOSSOCIAL" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql20 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql20) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }                                
                                ?>
                            </select>
                        </td>
                        <td class="text-center"><input type="date" id="comp_anti_Hbs" name="comp_anti_Hbs"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_anti_Hbs" name="status_anti_Hbs" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql21 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql21) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }                                
                                ?>
                            </select>
                        </td>
                        <td class="text-center"><input type="date" id="comp_HBs_Ag" name="comp_HBs_Ag"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_HBs_Ag" name="status_HBs_Ag" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql22 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql22) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }                                
                                ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">Anti-HBc</td>                        
                    </tr>
                    <tr>                        
                        <td class="text-center"><input type="date" id="comp_Anti_HBc" name="comp_Anti_HBc"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_Anti_HBc" name="status_Anti_HBc" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql23 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql23) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                Database::disconnect();
                                ?>
                            </select>
                        </td>
                    </tr>
                </table>
                <div class="form-inline" id="complementar_error"></div>
            </div>
        </div>
        <div class="form-group">
            <button class="btn btn-primary btn-danger" id="button" type="button">Fizeram Periódico <span class="glyphicon glyphicon-save" aria-hidden="true"></span></button>
        </div>
    </div>
    <div class="widget-content padding">
        <p class="text-center text-box">Azul -> Foi marcado tanto como correto, <strong>quanto</strong> com erro amiguinho!!</p>
        <p class="text-center text-box">Vermelho -> não recebeu nenhum tipo de marcação!!</p>
    </div>
    <div class="widget-content padding" id="periodico"></div>
</div>