<?php
session_start();
?>
<script src="../js/JQuery/jquery-1.11.1.min.js"></script><!--sempre chamar, com jquery ui o $ajax não funciona-->
<script src="../js/JQuery/jquery-ui-1.11.2.custom/jquery-ui.js"></script><!--sempre chamar, com jquery ui o $ajax não funciona-->
<script>
    $(document).ready(function () {

        $('#empresa').change(function () {
            $('#estabelecimento').load('../Controller/combo_estabelecimento.php?empresa=' + $('#empresa').val());
        });

        $('#button').css("display", "none");
        $('#datadoperiodico').css("display", "none");
        
        var esportes = [
		"1 - B001 SUPER CASA AMARELA","1 - B002 TODO DIA CARPINA","1 - B004 SUPER PARQUE AMORIM",
                "1 - B005  SUPER ARRUDA I","1 - B006  SUPER BOA VIAGEM I","1 - B007  TODO DIA AFOGADOS","1 - B009  HIPER CAXANGA",
                "1 - B010  SUPER CASA CAIADA","1 - B014  HIPER BUARQUE DE MACEDO","1 - B016 SUPER CASTRO PINTO","1 - B017  SUPER AFLITOS",
                "1 - B018  SUPER CEASA MACEIO","1 - B019  SUPER PIEDADE","1 - B020  HIPER CAMPINA GRANDE","1 - B021  SUPER PAJUCARA",
                "1 - B022  SUPER FAROL","1 - B023  SUPER BOMPRECO MERCADO","1 - B027 SUPER PONTA VERDE","1 - B028  SUPER CAMPINA GRANDE II",
                "1 - B029  HIPER MIRANTE","1 - B031  SUPER BENFICA","1 - B033  SUPER EPITACIO PESSOA","1 - B034  HIPER JOAO PESSOA",
                "1 - B035  SUPER BOA VIAGEM II","1 - B037  HIPER LAGOA","1 - B038  SUPER MANAIRA","1 - B039 TODO DIA CRUZ DAS ARMAS",
                "1 - B040 TODO DIA RIO DOCE","1 - B041  SUPER SHOPPING CENTER","1 - B043 SUPER COCO","1 - B044 TODO DIA GOIANA",
                "1 - B046 TODO DIA SANTA RITA","1 - B048 TODO DIA BAYEUX","1 - B049 TODO DIA GARANHUNS","1 - B058  TODO DIA PAULISTA",
                "1 - B063 TODO DIA CAMPINA GRANDE","1 - B068 SUPER ALDEOTA","1 - B070 CD MARANHAO","1 - B072 TODO DIA GRAVATA",
                "1 - B073 SUPER VERMELHO","1 - B074 SUPER PONTA NEGRA","1 - B093  MAGAZINE RECIFE","1 - B094  HIPER FORTALEZA",
                "1 - B096  HIPER GUARARAPES","1 - B102  HIPER BEZERRA DE MENEZES","1 - B105 SUPER DIONISIO TORRES",
                "1 - B106 TODO DIA IGARASSU","1 - B109 TODO DIA BANCARIO","1 - B118 HIPER FATIMA","1 - B121  HIPER NATAL",
                "1 - B122  HIPER PONTA NEGRA I","1 - B126  SUPER APICUM","1 - B128  SUPER COHAB","1 - B130  SUPER OURIQUE",
                "1 - B131  SUPER JABOATAO","1 - B132  SUPER SAO FRANCISCO","1 - B134  SUPER OLHO D AGUA","1 - B136 TODO DIA AGUAS COMPRIDAS",
                "1 - B137 TODO DIA NOVA DESCOBERTA","1 - B140  HIPER CALHAU","1 - B144  HIPER MOSSORO","1 - B145  SUPER TERESINA",
                "1 - B159  TODO DIA CAMARAGIBE","1 - B160  SUPER JANGA","1 - B166 TODO DIA CAVALEIRO I","1 - B214  TODO DIA CABO",
                "1 - B256  SUPER CANDEIAS","1 - B266 CEDIM MURIBECA","1 - B270  HIPER FAROL","1 - B271  HIPER JATIUCA",
                "1 - B297  MAGAZINE SHOPPING IGUATE","1 - B310  HIPER CASA FORTE","1 - B313 HIPER JUAZEIRO DO NORTE",
                "1 - B314  HIPER TERESINA II","1 - B315 HIPER BOMPRECO WASHINGTON","1 - B320 HIPER AV RECIFE","1 - B321 TODO DIA PEIXINHOS",
                "1 - B327  TODO DIA SAO LOURENCO II","1 - B328  TODO DIA ABREU E LIMA","1 - B330  TODO DIA PRAZERES",
                "1 - B333 TODO DIA VITORIA DE SANTO","1 - B334  TODO DIA AREIAS","1 - B337  HIPER TACARUNA","1 - B339  HIPER CARUARU",
                "1 - B341  HIPER BOA VIAGEM","1 - B343 FARMACIA BOA VIAGEM","1 - B344  FARMACIA TACARUNA","1 - B346 FARMACIA CAXANGA",
                "1 - B347 FARMACIA AFOGADOS","1 - B350 HIPER OLINDA","1 - B352  SUPER  ESPINHEIRO","1 - B354 FARMACIA ESPINHEIRO",
                "1 - B355  HIPER TERESINA","1 - B361  SUPER PETROLINA","1 - B363 FARMACIA GUARARAPES","1 - B370 FARMACIA CASA AMARELA",
                "1 - B371 FARMACIA PARQUE AMORIM","1 - B372 FARMACIA ARRUDA","1 - B373 FARMACIA SUPER BOA VIAGEM","1 - B375 FARMACIA SH RECIFE",
                "1 - B379 FARMACIA  PRAZERES","1 - B388 FARMACIA CASA FORTE","1 - B392 FARMACIA AFLITOS","1 - B393 FARMACIA AV RECIFE",
                "1 - B394 FARMACIA BENFICA","1 - B397  HIPER PETROLINA","1 - B398 FARMACIA IGARASSU","1 - B407 TODO DIA TURU",
                "1 - B408 HIPER ANTARES","1 - B409 SUPER TODO DIA PENEDO","1 - B417 FARMACIA JABOATAO","1 - B421 FARMACIA ABREU E LIMA",
                "1 - B422 FARMACIA VITORIA DE SANTO","1 - B424 FARMACIA OLINDA","1 - B441 FARMACIA GOIANA","1 - B443 FARMACIA PESQUEIRA",
                "1 - B445 TODO DIA VARGEM GRANDE","1 - B447 TODO DIA IPOJUCA","1 - B453 TODO DIA LIMOEIRO","1 - B455 TODO DIA BARRA DE JANGADA",
                "1 - B456 TODO DIA GEISEL","1 - B458 TODO DIA SANTA LUCIA","1 - B459 TODO DIA CLIMA BOM","1 - B460 TODO DIA JARDIM PIEDADE",
                "1 - B461 TODO DIA ARAPIRACA","1 - B462 TODO DIA ARAPIRACA II","1 - B463 TODO DIA JACINTINHO",
                "1 - B465 TODO DIA BAIRRO DOS ESTAD","1 - B466 TODO DIA PALMEIRA DOS IND","1 - B467 TODO DIA TIMBI",
                "1 - B469 TODO DIA BULTRINS","1 - B472 TODO DIA SURUBIM","1 - B473 TODO DIA SANTANA DO IPANE","1 - B474 TODO DIA CABEDELO",
                "1 - B476 TODO DIA PEDRAS DE FOGO","1 - B477 TODO DIA PRATA","1 - B478 TODO DIA BEZERROS","1 - B479 TODO DIA TIMBAUBA",
                "1 - B481 TODO DIA VILLAGE CAMPESTR","1 - B482 TODO DIA PESQUEIRA","1 - B483 TODO DIA MAMANGUAPE","1 - B486 TODO DIA GAMELEIRA",
                "1 - B487 TODO DIA ABREU E LIMA III","1 - B488 TODO DIA ESCADA","1 - B490 TODO DIA BELO JARDIM","1 - B491 TODO DIA PAU AMARELO",
                "1 - B492 TODO DIA VILA RICA","1 - B493 TODO DIA SAPE","1 - B494 TODO DIA NAZARE DA MATA","1 - B495 TODO DIA UNIAO DOS PALMAR",
                "1 - B496 TODO DIA CORURIPE","1 - B497 TODO DIA TEOTONIO VILELA","1 - B498 TODO DIA JARDIM SAO CRIST","1 - B499 TODO DIA ARARI",
                "1 - B640 TODO DIA MORENO","1 - B649 TODO DIA SANTA RITA","1 - B888 ESC REG RECIFE","1 - HIPER TD VITORIA DE STO ANTAO",
                "1 - HIPER TODO DIA PAULISTA","1 - SUPER TODO DIA ITAPECURU MIRIM","1 - TODO DIA EUSTAQUIO GOMES",
                "4 - B446 TODO DIA N S DA GLORIA","4 - B502 TODO DIA CAMACARI","4 - B503  SUPER POLITEAMA",
                "4 - B504  SUPER JARDINS","4 - B505 TODO DIA CASTELO BRANCO","4 - B506 TODO DIA SAO CRISTOVAO","4 - B510  HIPER JARDINS",
                "4 - B511 SUPER BOA VISTA DE BROTAS","4 - B512  TODO DIA LIBERDADE","4 - B513  SUPER LARGO DO PAPAGAIO",
                "4 - B514  SUPER PITUBA","4 - B515  SUPER CHAME-CHAME","4 - B517 HIPER ROTULA","4 - B518  SUPER NAZARE",
                "4 - B520  HIPER BONOCO","4 - B521  SUPER CAMPINAS DE BROTAS","4 - B522  SUPER SH SALVADOR","4 - B523  TODO DIA  RODOVIARIA",
                "4 - B524 SUPER  IAPI","4 - B525  SUPER CANELA","4 - B528  HIPER IGUATEMI","4 - B529  SUPER BOM DESPACHO",
                "4 - B530 SUPER SAO RAFAEL","4 - B531 TODO DIA SUSSUARANA","4 - B532 TODO DIA URUGUAI","4 - B533 TODO DIA SAO CAETANO",
                "4 - B535 TODO DIA MAL RONDON","4 - B537 TODO DIA ALAGOINHAS","4 - B538 TODO DIA TANCREDO NEVES",
                "4 - B539 TODO DIA CRUZ DAS ALMAS","4 - B540  HIPER FEIRA DE SANTANA","4 - B541 TODO DIA STO ANTONIO DE J",
                "4 - B543  TODO DIA PARIPE","4 - B552 SUPER FONTE NOVA","4 - B554  SUPER RIO VERMELHO","4 - B556  SUPER BOCA DO RIO",
                "4 - B558  SUPER ITAPOAN","4 - B559  TODO DIA PERNAMBUES","4 - B560 SUPER SAO CAETANO","4 - B562  SUPER ITAIGARA",
                "4 - B563  HIPER GARIBALDI","4 - B564  HIPER CABULA","4 - B565  SUPER CAMACARI","4 - B570  TODO DIA SIMOES FILHO",
                "4 - B571  SUPER BARRA AVENIDA","4 - B572  TODO DIA  PERIPERI","4 - B575  TODO DIA COSME DE FARIAS",
                "4 - B576  SUPER PAU DA LIMA","4 - B577  HIPER LITORAL NORTE","4 - B578  SUPER JARDIM ARMACAO",
                "4 - B579  SUPER VASCO DA GAMA","4 - B580  SUPER MANOEL DIAS","4 - B581  SUPER MATATU BROTAS",
                "4 - B582  SUPER BARRA","4 - B584  HIPER VITORIA DA CONQUIS","4 - B585  HIPER ITABUNA","4 - B586  TODO DIA DIAS D AVILA",
                "4 - B587 SUPER LAURO DE FREITAS","4 - B589  SUPER PLATAFORMA","4 - B593  HIPER ARACAJU","4 - B595  SUPER SANEAMENTO",
                "4 - B596  SUPER RODOVIARIA","4 - B598 SUPER  CANDEIAS","4 - B599  SUPER SIQUEIRA CAMPOS SE","4 - B602 TODO DIA CIDADE NOVA",
                "4 - B603 TODO DIA LAGARTO","4 - B604 TODO DIA ESTANCIA","4 - B606  TODO DIA FAZENDA GRANDE","4 - B607 TODO DIA SANTO AMARO",
                "4 - B608 TODO DIA SAO CONRADO","4 - B609 TODO DIA N S DO SOCORRO","4 - B610 TODO DIA PONTO NOVO","4 - B611 TODO DIA BUGIO",
                "4 - B612 TODO DIA PROPRIA","4 - B613 TODO DIA TOMBA","4 - B614 TODO DIA KALILANDIA","4 - B615 TODO DIA SR DOS PASSOS",
                "4 - B616 TODO DIA SERRINHA","4 - B617 TODO DIA SANTO ESTEVAO","4 - B618 TODO DIA VALENCA","4 - B619 TODO DIA AGUAS CLARAS",
                "4 - B620 TODO DIA CIA I","4 - B621 TODO DIA CARLOS GOMES","4 - B622 TODO DIA AMARGOSA","4 - B623 TODO DIA MATA ESCURA",
                "4 - B624 TODO DIA VERA CRUZ","4 - B625 TODO DIA ESPLANADA","4 - B626 TODO DIA POJUCA","4 - B632 TODO DIA CASTRO ALVES",
                "4 - B633 TODO DIA SAO GONCALO DOS","4 - B634 TODO DIA ENTRE RIOS","4 - B635 TODO DIA BOQUIM",
                "4 - B636 TODO DIA MATA DE SAO JOAO","4 - B637 TODO DIA MURITIBA","4 - B638 TODO DIA ITABERABA",
                "4 - B641 TODO DIA BAIXA DE QUINTAS","4 - B642 TODO DIA PIRAJA","4 - B643 TODO DIA VALERIA","4 - B644 TODO DIA RIO REAL",
                "4 - B645 TODO DIA CASTELO BRANCO","4 - B646 TODO DIA CAMACARI","4 - B647 TODO DIA DIAS D AVILA II",
                "4 - B648 SUPER TD CONCEICAO COITE","4 - B651 TODO DIA ESTRADA BARREIRA","4 - B660 CENTRAL DE PADARIA BAHIA",
                "4 - CD PIRAJA BA","5 - TRANSPORTADORA - BAHIA","5 - TRANSPORTADORA - BARUERI -SP","5 - TRANSPORTADORA - PINHAIS",
                "5 - TRANSPORTADORA BOMPRECO LTDA","280 - TRANSPORTADORA - BETIM","450 - CENTRO DISTRIBUICAO BARUERI",
                "450 - CENTRO DISTRIBUICAO BETIM","450 - CENTRO DISTRIBUICAO CONDE","450 - CENTRO DISTRIBUICAO EMBU",
                "450 - DROGARIA HIPER ANTARES","450 - DROGARIA HIPER TAUBATE","450 - DROGARIA HTD VITORIA  STO ANTÃ",
                "450 - DROGARIA SC CAMPO GRANDE","450 - DROGARIA SUPER VITORIA","450 - DROGARIA WM SUMARE","450 - FAMARCIA BIG PELOTAS",
                "450 - FAMARCIA MAXXI PELOTAS","450 - FARMACIA  MAXXI OLINDA","450 - FARMACIA AMERICANA","450 - FARMACIA ARARAS",
                "450 - FARMACIA ASA NORTE","450 - FARMACIA BIG BAGE","450 - FARMACIA BIG BLUMENAU","450 - FARMACIA BIG BLUMENAU NORTE",
                "450 - FARMACIA BIG BRUSQUE","450 - FARMACIA BIG CAMPO MOURAO","450 - FARMACIA BIG CAPOEIRAS",
                "450 - FARMACIA BIG CAXIAS DO SUL","450 - FARMACIA BIG CHAPECO","450 - FARMACIA BIG GRAVATAI",
                "450 - FARMACIA BIG JK FOZ DO IGUACU","450 - FARMACIA BIG JOINVILLE","450 - FARMACIA BIG LONDRINA",
                "450 - FARMACIA BIG MARINGA CATUAI","450 - FARMACIA BIG PINHEIRINHO","450 - FARMACIA BIG SANTA CRUZ",
                "450 - FARMACIA BIG SANTA MARIA","450 - FARMACIA BIG SAO LEOPOLDO","450 - FARMACIA BIG SAPIRANGA",
                "450 - FARMACIA BIG SERTORIO","450 - FARMACIA BIG STA MARIA PATRONA","450 - FARMACIA BIG TOLEDO",
                "450 - FARMACIA BIG UMUARAMA","450 - FARMACIA BIG URUGUAIANA","450 - FARMACIA BIG ZONA SUL",
                "450 - FARMACIA CAMPOS DOS GOYTACAZES","450 - FARMACIA DIADEMA","450 - FARMACIA GOIANIA NORTE",
                "450 - FARMACIA GRANJA VIANA","450 - FARMACIA HBP  CABULA","450 - FARMACIA HBP BUARQUE DE MACEDO",
                "450 - FARMACIA HBP FAROL II","450 - FARMACIA HBP GARIBALDI","450 - FARMACIA HBP JATIUCA",
                "450 - FARMACIA HBP LAGOA NOVA","450 - FARMACIA HBP PONTA NEGRA","450 - FARMACIA HIPER ARACAJU",
                "450 - FARMACIA HIPER ASSIS","450 - FARMACIA HIPER AVENIDA PARANA","450 - FARMACIA HIPER C.GRANDE BOSQUE",
                "450 - FARMACIA HIPER CATANDUVA","450 - FARMACIA HIPER CAXANGA","450 - FARMACIA HIPER INDAIATUBA",
                "450 - FARMACIA HIPER JARDINS","450 - FARMACIA HIPER MOGI GUACU","450 - FARMACIA HIPER PASSOS",
                "450 - FARMACIA HIPER PATOS DE MINAS","450 - FARMACIA HIPER SANTO ANDRE","450 - FARMACIA HIPER VOLTA REDONDA",
                "450 - FARMACIA HIPERMERCADO TORRES","450 - FARMACIA HTD PAULISTA MARANG.","450 - FARMACIA INDIANOPOLIS",
                "450 - FARMACIA LIMEIRA","450 - FARMACIA MACAE","450 - FARMACIA MAXXI BAURU","450 - FARMACIA MAXXI ITAJAI",
                "450 - FARMACIA MAXXI LAGES","450 - FARMACIA MAXXI LAJEADO","450 - FARMACIA MAXXI LONDRINA",
                "450 - FARMACIA MAXXI NOVO HAMBURGO","450 - FARMACIA MAXXI VIAMAO","450 - FARMACIA MORUMBI",
                "450 - FARMACIA NAC BENTO GONCALVES","450 - FARMACIA NAC GRAVATAI","450 - FARMACIA NAC LUCAS DE OLIVEIRA",
                "450 - FARMACIA NAC SANTA ROSA","450 - FARMACIA NACIONAL FLORENCIO AB","450 - FARMACIA NACIONAL IMBE",
                "450 - FARMACIA NACIONAL TERESOPOLIS","450 - FARMACIA POSTO CONTAGEM","450 - FARMACIA PRESIDENTE PRUDENTE",
                "450 - FARMACIA S JOSE DO RIO PRETO","450 - FARMACIA SAO JOSE DOS CAMPOS","450 - FARMACIA SBP  CANELA",
                "450 - FARMACIA SBP  PITUBA","450 - FARMACIA SBP  VASCO DA GAMA","450 - FARMACIA SBP BARRO VERMELHO",
                "450 - FARMACIA SBP FAROL I","450 - FARMACIA SBP IAPI","450 - FARMACIA SBP PAJUCARA","450 - FARMACIA SBP0PONTA VERDE",
                "450 - FARMACIA SC FATIMA","450 - FARMACIA SC MARILIA","450 - FARMACIA SC PAMPULHA","450 - FARMACIA SC PIRACICABA",
                "450 - FARMACIA SC SHOPPING DOM PEDRO","450 - FARMACIA SC SHOPPING OUTLET","450 - FARMACIA SC SOROCABA",
                "450 - FARMACIA SC VILA GUILHERME","450 - FARMACIA SC W SOARES","450 - FARMACIA STD CONCEICAO COITE",
                "450 - FARMACIA STD PENEDO","450 - FARMACIA SUPER AFLITOS","450 - FARMACIA SUPER AGUAS CLARAS",
                "450 - FARMACIA SUPER BENFICA","450 - FARMACIA SUPER BOA VIAGEM","450 - FARMACIA SUPER CANDEIAS",
                "450 - FARMACIA SUPER CASA AMARELA","450 - FARMACIA SUPER DOMIN FERREIRA","450 - FARMACIA SUPER JANGA",
                "450 - FARMACIA SUPER JARDINS","450 - FARMACIA SUPER PETROLINA","450 - FARMACIA SUPER PIEDADE",
                "450 - FARMACIA SUPER SANEAMENTO","450 - FARMACIA SUPER SHOPPING RECIFE","450 - FARMACIA SUPER SIQUEIRA CAMPOS",
                "450 - FARMACIA SUPERC ARRUDA I","450 - FARMACIA SUPERCENTER BAURU","450 - FARMACIA SUPERCENTER BRASILIA",
                "450 - FARMACIA SUPERCENTER FRANCA","450 - FARMACIA SUPERCENTER GOIANIA","450 - FARMACIA SUPERCENTER GUARULHOS",
                "450 - FARMACIA SUPERCENTER HORTOLAND","450 - FARMACIA SUPERCENTER ITU","450 - FARMACIA SUPERCENTER JACAREI",
                "450 - FARMACIA SUPERCENTER SAO BERNA","450 - FARMACIA TAMBORE","450 - FARMACIA TD  RODOVIARIA",
                "450 - FARMACIA TD ABREU E LIMA","450 - FARMACIA TD AFOGADOS","450 - FARMACIA TD ALTO DO BOQUEIRAO",
                "450 - FARMACIA TD CAMARAGIBE","450 - FARMACIA TD CAMPANARIO","450 - FARMACIA TD CAMPO BOM",
                "450 - FARMACIA TD CANOAS EST VELHA","450 - FARMACIA TD CANUDOS","450 - FARMACIA TD CANUDOS I",
                "450 - FARMACIA TD CARPINA","450 - FARMACIA TD CAVALEIRO","450 - FARMACIA TD ESPLANADA",
                "450 - FARMACIA TD LAGARTO","450 - FARMACIA TD LAPA","450 - FARMACIA TD PARANAGUA","450 - FARMACIA TD PAULISTA",
                "450 - FARMACIA TD PERNAMBUES","450 - FARMACIA TD PINHAIS","450 - FARMACIA TD PONTA GROSSA",
                "450 - FARMACIA TD RIO DOCE","450 - FARMACIA TD ROSEIRA PARK","450 - FARMACIA TD SAO CRISTOVAO",
                "450 - FARMACIA TD SAO LOURENCO II","450 - FARMACIA TD SUSSUARANA","450 - FARMACIA TD VITORIA STO ANTAO",
                "450 - FARMACIA TODO DIA PROPRIA","450 - FARMACIA UBERABA","450 - FARMACIA UBERLANDIA","450 - FARMACIA VL LEOPOLDINA",
                "450 - FARMACIA WASHINGTON LUIS","450 - HIPER INDAIATUBA","450 - HIPER TAUBATE","450 - HO","450 - SAMS AGUAS CLARAS",
                "450 - SAMS BARIGUI","450 - SAMS BOM RETIRO","450 - SAMS BRASILIA","450 - SAMS CAMPINAS","450 - SAMS CONTAGEM",
                "450 - SAMS CURITIBA","450 - SAMS FORTALEZA","450 - SAMS GOIANIA","450 - SAMS GUARULHOS","450 - SAMS MACEIO","450 - SAMS NATAL",
                "450 - SAMS NITEROI","450 - SAMS OSASCO","450 - SAMS RADIAL","450 - SAMS RECIFE","450 - SAMS RIBEIRAO PRETO",
                "450 - SAMS RJ","450 - SAMS S C SUL","450 - SAMS S J CAMPOS","450 - SAMS SALVADOR","450 - SAMS SAO BERNARDO DO CAMPO",
                "450 - SAMS SERTORIO","450 - SAMS STO AMARO","450 - SAMS STO ANDRE","450 - SAMS TAMBORE","450 - SAMS VITORIA",
                "450 - SUPERC AGUAS CLARAS","450 - SUPERC AMERICANA","450 - SUPERC ARARAS","450 - SUPERC ARICANDUVA",
                "450 - SUPERC ARTHUR BERNARDES","450 - SUPERC ASSIS","450 - SUPERC BAURU","450 - SUPERC BRASILIA",
                "450 - SUPERC BRASILIA ASA NORTE","450 - SUPERC C.GRANDE BOSQUE IPES","450 - SUPERC CABRAL","450 - SUPERC CAMPINAS OUT LET",
                "450 - SUPERC CAMPINAS SHOPPING DOM P","450 - SUPERC CAMPO GRANDE","450 - SUPERC CAMPOS DOS GOYTACAZES",
                "450 - SUPERC CATANDUVA","450 - SUPERC CENTRAL PLAZA","450 - SUPERC CONTAGEM","450 - SUPERC COTIA",
                "450 - SUPERC CURITIBA","450 - SUPERC FRANCA","450 - SUPERC GOIANIA","450 - SUPERC GOIANIA NORTE",
                "450 - SUPERC GUARULHOS","450 - SUPERC HORTOLANDIA","450 - SUPERC INDIANOPOLIS","450 - SUPERC ITU",
                "450 - SUPERC LIMEIRA","450 - SUPERC LONDRINA","450 - SUPERC MACAE","450 - SUPERC MARILIA",
                "450 - SUPERC MOGI GUACU","450 - SUPERC MORUMBI","450 - SUPERC OSASCO","450 - SUPERC PACAEMBU",
                "450 - SUPERC PAMPULHA","450 - SUPERC PASSOS","450 - SUPERC PATOS DE MINAS","450 - SUPERC PIRACICABA",
                "450 - SUPERC PRESIDENTE PRUDENTE","450 - SUPERC RIB PRETO","450 - SUPERC RIO DE JANEIRO","450 - SUPERC S B CAMPO",
                "450 - SUPERC S J CAMPOS","450 - SUPERC SAO JOSE DO RIO PRETO","450 - SUPERC SOROCABA","450 - SUPERC STO ANDRE",
                "450 - SUPERC SUMARE","450 - SUPERC TAMBORE","450 - SUPERC UBERABA","450 - SUPERC UBERLANDIA",
                "450 - SUPERC VILA GUILHERME","450 - SUPERC VILA LEOPOLDINA","450 - SUPERC VITORIA","450 - SUPERC VOLTA REDONDA",
                "450 - SUPERC WASHINGTON LUIS","450 - SUPERCENTER JACAREI","450 - TODO DIA ACHIOLE","450 - TODO DIA ALTO DE ITAQUAQUECETU",
                "450 - TODO DIA BARAO DE MAUA","450 - TODO DIA CAMPOS ELISEOS","450 - TODO DIA CARAPICUIBA -VILA CRE",
                "450 - TODO DIA CARAPICUIBA BETSAIDA","450 - TODO DIA CARAPICUIBA GOPIUVA","450 - TODO DIA DIADEMA CAMPANARIO",
                "450 - TODO DIA DIADEMA VILA NOGUEIRA","450 - TODO DIA GUARULHOS - WALTER RI","450 - TODO DIA INDEPENDENCIA",
                "450 - TODO DIA JARDIM BRASILIA","450 - TODO DIA JD SAO LUIS","450 - TODO DIA MOGI DAS CRUZES MOGIL",
                "450 - TODO DIA OSASCO AYROSA","450 - TODO DIA OURO VERDE","450 - TODO DIA PALMEIRAS",
                "450 - TODO DIA ROSEIRA PARK CARAPICU","450 - TODO DIA SAID CAPAO REDONDO","450 - TODO DIA SANTO ANDRE- PALMARES",
                "450 - TODO DIA SAO MATEUS","450 - TODO DIA SAO PAULO JD JORDANIA","450 - TODO DIA SAO PAULO NORDESTINA",
                "450 - TODO DIA SAO VICENTE - MARGARI","450 - TODO DIA SAPOPEMBA","450 - TODO DIA SERRARIA",
                "450 - TODO DIA SETE LAGOAS","454 - CENTRO DE DISTR ECOM RECIFE","454 - CENTRO DISTRIBUICAO CAJAMAR",
                "454 - CENTRO DISTRIBUICAO VESPASIANO","454 - WMB COMERCIO ELETRONICO","457 - CENTRO DE DISTRIBUICAO FARMA",
                "10001 - ADMINISTRACAO LOGISTICA","10001 - ADMINISTRACAO LOGISTICA","10001 - ADMINISTRACAO MERCADORAMA",
                "10001 - ADMINISTRACAO MERCADORAMA","10001 - ADMINISTRACAO MERCADORAMA","10001 - ADMINISTRACAO MERCADORAMA",
                "10001 - ADMINISTRACAO MERCADORAMA","10001 - ADMINISTRACAO NACIONAL","10001 - ADMINISTRACAO NACIONAL",
                "10001 - ADMINISTRACAO NACIONAL","10001 - ADMINISTRACAO NACIONAL","10001 - ADMINISTRACAO NACIONAL",
                "10001 - ADMINISTRACAO NACIONAL","10001 - ADMINISTRACAO NACIONAL","10001 - ADMINISTRACAO NACIONAL",
                "10001 - ADMINISTRACAO NACIONAL","10001 - ADMINISTRACAO NACIONAL","10001 - ADMINISTRACAO NACIONAL",
                "10001 - ADMINISTRACAO NACIONAL","10001 - ADMINISTRACAO NACIONAL","10001 - ADMINISTRACAO NACIONAL",
                "10001 - ADMINISTRACAO NACIONAL","10001 - ADMINISTRACAO NACIONAL","10001 - ADMINISTRACAO NACIONAL",
                "10001 - ADMINISTRACAO NACIONAL","10001 - ADMINISTRACAO TODO DIA","10001 - ADMINISTRACAO TODO DIA",
                "10001 - ADMINISTRACAO TODO DIA","10001 - ADMINISTRACAO TODO DIA","10001 - ADMINISTRATIVO ISD",
                "10001 - ARQUIVO CENTRAL","10001 - ASSESSORIA IMPRENSA","10001 - AUDITORIA - CORP",
                "10001 - BIG 003 FLORIANOPOLIS CAPOEIRAS C0003  ","10001 - BIG 004 JOINVILLE AMERICA C0406",
                "10001 - BIG 005 R.GRANDE SEN.CORREA C0506    ","10001 - BIG 006 CTBA AV. DAS TORRES C0606",
                "10001 - BIG 007 POA CRISTAL C0706","10001 - BIG 010 CACHOEIRINHA F.CUNHA 4000 C1066 ",
                "10001 - BIG 018 N.HAMBURGO N.BECKER C1806","10001 - BIG 025.MARIA N.SRA.LOURDES C0025",
                "10001 - BIG 044 CTBA PORTAO C0044","10001 - BIG 047 MARINGA TUIUTI C0047","10001 - BIG 053 CTBA B.VISTA C0053",
                "10001 - BIG 055 CTBA XAXIM 2973 C0055","10001 - BIG 071 CTBA STA.FELICIDADE C0071",
                "10001 - BIG 075 CANOAS G.SCHELL 9000 C0075","10001 - BIG 076 FOZ JK DE OLIVEIRA C0076","10001 - BIG 079 POA SERTORIO C0079",
                "10001 - BIG 083 S.LEOPOLDO PINHEIRO C0083","10001 - BIG 090 CTBA PINHEIRINHO C0090",
                "10001 - BIG 091 ALVORADA AGUA VIVA C0091","10001 - BIG 092 CAXIAS M.HERVAL C0092",
                "10001 - BIG 096 VIAMAO S.CECILIA C0966","10001 - BIG 097 JOINVILLE A.GARIBALDI C0097",
                "10001 - BIG 123 BLUMENAU BAIRRO DA VELHA C0123","10001 - BIG 150 LIVRAMENTO C0150",
                "10001 - BIG 155 URUGUAIANA D.CAXIAS C0155","10001 - BIG 200 CAMBORIU C0200","10001 - BIG 202 PELOTAS C0202 ",
                "10001 - BIG 205 ESTEIO CENTRO C0205","10001 - BIG 208 GRAVATAI C1059","10001 - BIG 209 IGUATEMI C1038",
                "10001 - BIG 210 POA ZONA SUL C1043","10001 - BIG 271 MARINGA PR C1255","10001 - BIG 299 UMUARAMA PR C1325",
                "10001 - BIG 310 SANTA CRUZ RS C1346","10001 - BIG 336 BRUSQUE SC C1365","10001 - BIG 341 SAPIRANGA C1394",
                "10001 - BIG 354 CAMPO MOURAO PR C1449","10001 - BIG 375 BLUMENAU C1475","10001 - BIG 383 TOLEDO / PR",
                "10001 - BIG 383 TOLEDO / PR - SEG","10001 - BIG 383 TOLEDO PR - LIMP","10001 - BIG 385 STA MARIA PATR (FOTO)",
                "10001 - BIG 385 STA MARIA PATR (LIMPE)","10001 - BIG 385 STA MARIA PATR (MANUT)","10001 - BIG 385 STA MARIA PATR (SEG)",
                "10001 - BIG 385 STA MARIA PATRONATO","10001 - BIG 394 CHAPECO / SC","10001 - BIG 394 CHAPECO / SC - FOTO",
                "10001 - BIG 394 CHAPECO / SC - LIMP","10001 - BIG 394 CHAPECO / SC - RESTAUR","10001 - BIG 394 CHAPECO / SC - SEG",
                "10001 - BIG 396 LAGES","10001 - BIG 396 LAGES (FOTO)","10001 - BIG 396 LAGES (LIMPEZA)","10001 - BIG 396 LAGES (SEG)",
                "10001 - BIG BAGE 382","10001 - BIG BAGE 382 - LIMP","10001 - BIG BAGE 382 - SEG","10001 - BIG BAGE 382 FOTOCENTER",
                "10001 - BIG PONTA GROSSA-LIMP","10001 - BIG PONTA GROSSA-SEG","10001 - CD 425","10001 - CD 430 NOVA SANTA RITA",
                "10001 - CD 430 NOVA SANTA RITA - SEG","10001 - CD COLOMBO ARUBA","10001 - CD MAXXI - CACHOEIRINHA",
                "10001 - CD MAXXI - CACHOEIRINHA SEG","10001 - CD MAXXI 431 SALVADOR","10001 - CD MAXXI 433 CAMBORIU - SEG",
                "10001 - CD MAXXI 433 CAMBORIU-MANUT","10001 - CD MAXXI CAMBORIU","10001 - CD MAXXI EMBU - SEG","10001 - CD MAXXI EMBU - SP",
                "10001 - CD MAXXI RECIFE","10001 - CD MAXXI RECIFE - SEG","10001 - CD MONTENEGRO","10001 - CD PINHAIS - LOG REVERSA",
                "10001 - CD PINHAIS PR","10001 - CD PINHAIS PR - SEG","10001 - CD PINHAIS PR-DESC","10001 - CD PINHAIS PR-MANUT",
                "10001 - CD SERTORIO","10001 - CD SERTORIO","10001 - CD SERTORIO","10001 - CD SERTORIO","10001 - CD SERTORIO-LOGISTICA REVERSA",
                "10001 - CD SERTORIO-MANUT","10001 - CD SERTORIO-SEG","10001 - CD SERTORIO-SEG","10001 - CENTRAL PEREC ESTEIO",
                "10001 - CH - ADM PESSOAL","10001 - CH - TREINAMENTO E DESENV","10001 - COMERCIAL","10001 - CONSTRUCOES",
                "10001 - CORPORATIVOS (OUTROS)","10001 - CORPORATIVOS (OUTROS)","10001 - CSC","10001 - CSC CAPITAL HUMANO",
                "10001 - CSC CONTABILIDADE","10001 - CSC FISCAL IMPOSTOS","10001 - CSC GESTAO DE SERVICOS","10001 - CSC TESOURARIA",
                "10001 - DESENVOLVIMENTO COMERCIAL","10001 - DESENVOLVIMENTO COMERCIAL","10001 - DIRECAO LOGISTICA",
                "10001 - DIRECAO LOGISTICA","10001 - DIRETORIA JURIDICA","10001 - DOWNSTREAM","10001 - DOWNSTREAM",
                "10001 - DOWNSTREAM - MAXXI","10001 - DOWNSTREAM - MAXXI","10001 - DOWNSTREAM - MAXXI","10001 - DOWNSTREAM - MAXXI",
                "10001 - ESTRUTURA COMERCIAL","10001 - EXPANSAO - CORP","10001 - EXPANSAO - CORP","10001 - EXPANSAO - CORP",
                "10001 - EXPANSAO - CORP","10001 - EXPANSAO - CORP","10001 - EXPANSAO - CORP","10001 - EXPANSAO - MANUTENCAO",
                "10001 - EXPANSAO TODO DIA","10001 - FARMACIA 641 MAXXI OLINDA","10001 - FINANCE INTEGRACAO","10001 - FINANCEIRO - CARTOES",
                "10001 - FINANCEIRO - CORP","10001 - GERENCIA TRANSP/DESENV LOGIST","10001 - HO MAXXI - SP",
                "10001 - HO MAXXI BAHIA","10001 - HO MAXXI BAHIA","10001 - HO MAXXI BAHIA","10001 - HO MAXXI BAHIA",
                "10001 - HO MAXXI RECIFE","10001 - HO MAXXI RECIFE","10001 - INFRA-ESTRUTURA","10001 - INFRA-ESTRUTURA",
                "10001 - INTEGRACAO","10001 - JURIDICO - ALVARAS","10001 - JURIDICO - ALVARAS","10001 - JURIDICO - PERMITS",
                "10001 - LOSS PREVENTION","10001 - LOSS PREVENTION","10001 - LOSS PREVENTION","10001 - MANUT GRUPO VALE DOS SINOS",
                "10001 - MANUT HIPER SUL CAPITAL","10001 - MANUTENCAO - BIG062","10001 - MANUTENCAO - MAXXI RS/SC",
                "10001 - MANUTENCAO - MAXXI RS/SC","10001 - MANUTENCAO - MAXXI RS/SC","10001 - MANUTENCAO - MAXXI RS/SC",
                "10001 - MANUTENCAO - MAXXI RS/SC","10001 - MANUTENCAO - MERC 026","10001 - MANUTENCAO - MERC 035",
                "10001 - MANUTENCAO - MERC 036","10001 - MANUTENCAO - MERC 038","10001 - MANUTENCAO - MERC 042",
                "10001 - MANUTENCAO - MERC 043","10001 - MANUTENCAO - MERC 046","10001 - MANUTENCAO - MERC 051",
                "10001 - MANUTENCAO - MERC 060","10001 - MANUTENCAO - MERC 061","10001 - MANUTENCAO - MERC 064",
                "10001 - MANUTENCAO - MERC 065 E 048","10001 - MANUTENCAO - MERC 068","10001 - MANUTENCAO - MERC 073",
                "10001 - MANUTENCAO - MERC 078","10001 - MANUTENCAO - MERC 081","10001 - MANUTENCAO - MERC 082",
                "10001 - MANUTENCAO - RS","10001 - MANUTENCAO BIG BAGE 382","10001 - MANUTENCAO BIG CHAPECO 394",
                "10001 - MANUTENCAO BIG TOLEDO 383","10001 - MANUTENCAO NAC B GONCALVES","10001 - MANUTENCAO NAC BAGE TUPY SILV",
                "10001 - MANUTENCAO NAC BARRA DO RIBEIR","10001 - MANUTENCAO NAC BOA VISTA","10001 - MANUTENCAO NAC BOA VISTA",
                "10001 - MANUTENCAO NAC C CANOA","10001 - MANUTENCAO NAC CACHOEIRINHA","10001 - MANUTENCAO NAC CANOAS",
                "10001 - MANUTENCAO NAC DOM PEDRITO","10001 - MANUTENCAO NAC EST 24 AGO","10001 - MANUTENCAO NAC ESTEIO V OLIMP",
                "10001 - MANUTENCAO NAC FLORIANOPOLIS","10001 - MANUTENCAO NAC GRAMADO","10001 - MANUTENCAO NAC GRAVATAI",
                "10001 - MANUTENCAO NAC GRAVATAI V BRCA","10001 - MANUTENCAO NAC GUAIBA-B-SCHELL","10001 - MANUTENCAO NAC GUAIBA-CENTRO",
                "10001 - MANUTENCAO NAC HAMB VELHO","10001 - MANUTENCAO NAC IJUI","10001 - MANUTENCAO NAC IMBE",
                "10001 - MANUTENCAO NAC METROP SUL FRON","10001 - MANUTENCAO NAC METROPOLITANA","10001 - MANUTENCAO NAC MONTENEGRO",
                "10001 - MANUTENCAO NAC N HMB PORTINHO","10001 - MANUTENCAO NAC OSORIO","10001 - MANUTENCAO NAC PEL B AZEVEDO",
                "10001 - MANUTENCAO NAC PEL LOBO COSTA","10001 - MANUTENCAO NAC PELOTAS","10001 - MANUTENCAO NAC PELOTAS",
                "10001 - MANUTENCAO NAC POA BOA VISTA","10001 - MANUTENCAO NAC POA C REDENTOR","10001 - MANUTENCAO NAC POA IGUATEMI",
                "10001 - MANUTENCAO NAC POA JD LEOPOLDI","10001 - MANUTENCAO NAC POA L OLIVEIRA","10001 - MANUTENCAO NAC POA M TOSTES",
                "10001 - MANUTENCAO NAC POA MEN DEUS","10001 - MANUTENCAO NAC POA MEN DEUS","10001 - MANUTENCAO NAC POA SANTANA",
                "10001 - MANUTENCAO NAC POA SANTANA","10001 - MANUTENCAO NAC POA TRISTEZA","10001 - MANUTENCAO NAC PRAIA DE BELAS",
                "10001 - MANUTENCAO NAC RIO GDE CASSINO","10001 - MANUTENCAO NAC ROSARIO","10001 - MANUTENCAO NAC S LEO CRISTO RE",
                "10001 - MANUTENCAO NAC S MARIA-MEDIANE","10001 - MANUTENCAO NAC S MARIA-MEDIANE","10001 - MANUTENCAO NAC SAO BORJA",
                "10001 - MANUTENCAO NAC SAO GABRIEL","10001 - MANUTENCAO NAC SAPUCAIA","10001 - MANUTENCAO NAC STA CRUZ CENTRO",
                "10001 - MANUTENCAO NAC STA ROSA-CENTRO","10001 - MANUTENCAO NAC STO ANGELO","10001 - MANUTENCAO NAC TORRES",
                "10001 - MANUTENCAO NAC TRAMANDAI","10001 - MANUTENCAO NAC VIAMAO","10001 - MANUTENCAO NAC XANGRILA",
                "10001 - MANUTENCAO NACIONAL LITORAL","10001 - MANUTENCAO NACIONAL PREMIUM","10001 - MANUTENCAO NACIONAL PREMIUM",
                "10001 - MANUTENCAO NACIONAL PREMIUM","10001 - MANUTENCAO NACIONAL STANDARD","10001 - MANUTENCAO NACIONAL STANDARD",
                "10001 - MANUTENCAO NACIONAL STANDARD","10001 - MANUTENCAO NACIONAL STANDARD","10001 - MANUTENCAO NACIONAL STANDARD",
                "10001 - MANUTENCAO SUPER PR","10001 - MANUTENCAO TODO DIA CAMPO BOM","10001 - MANUTENCAO TODO DIA CAMPO BOM","10001 - MARKETING - BIG RS",
                "10001 - MARKETING TODO DIA","10001 - MAXXI 223 VIAMAO","10001 - MAXXI 223 VIAMAO - LIMP","10001 - MAXXI 223 VIAMAO - SEG",
                "10001 - MAXXI 227 LAURO FREITAS","10001 - MAXXI 227 LAURO FREITAS-FARM","10001 - MAXXI 227 LAURO FREITAS-LIMP",
                "10001 - MAXXI 227 LAURO FREITAS-SEG","10001 - MAXXI 232 LONDRINA","10001 - MAXXI 232 LONDRINA - LIMP",
                "10001 - MAXXI 232 LONDRINA - SEG","10001 - MAXXI 237 TABOA DA SERRA - SEG","10001 - MAXXI 237 TABOA DA SERRA SP",
                "10001 - MAXXI 237 TABOAO DA SERRA LIMP","10001 - MAXXI 237 TABOAO DA SERRA MANU","10001 - MAXXI 246 MACEIO",
                "10001 - MAXXI 246 MACEIO - LIMP","10001 - MAXXI 246 MACEIO - SEG","10001 - MAXXI 247 SAPOPEMBA","10001 - MAXXI 250 LAGES",
                "10001 - MAXXI 250 LAGES - LIMP","10001 - MAXXI 250 LAGES - MANUT","10001 - MAXXI 250 LAGES - SEG","10001 - MAXXI 251 FOZ DO IGUACU",
                "10001 - MAXXI 253 ARAPIRACA - AL","10001 - MAXXI 253 ARAPIRACA - LIMP","10001 - MAXXI 253 ARAPIRACA - SEG",
                "10001 - MAXXI 254 MARACANAU","10001 - MAXXI 254 MARACANAU","10001 - MAXXI 254 MARACANAU - LIMP","10001 - MAXXI 254 MARACANAU - SEG",
                "10001 - MAXXI 256 CAMPINA GRANDE","10001 - MAXXI 256 CAMPINA GRANDE - LIM","10001 - MAXXI 256 CAMPINA GRANDE - SEG",
                "10001 - MAXXI 257 CHAPECO","10001 - MAXXI 257 CHAPECO - LIMP","10001 - MAXXI 257 CHAPECO - SEG","10001 - MAXXI 259 BAURU SP",
                "10001 - MAXXI 264 CAMPO GRANDE SUL","10001 - MAXXI 265 MONTES CLAROS - SEG","10001 - MAXXI 268 CRICIUMA","10001 - MAXXI 268 CRICIUMA - LIMP",
                "10001 - MAXXI 268 CRICIUMA - SEG","10001 - MAXXI 269 VITORIA DA CONQUISTA","10001 - MAXXI 276 PINHAIS",
                "10001 - MAXXI 276 PINHAIS","10001 - MAXXI 276 PINHAIS - LIMP","10001 - MAXXI 276 PINHAIS - SEG","10001 - MAXXI 281 OLINDA",
                "10001 - MAXXI 281 OLINDA - LIMP","10001 - MAXXI 281 OLINDA - SEG","10001 - MAXXI 283 LAJEADO/RS","10001 - MAXXI 283 LAJEADO/RS - FARM",
                "10001 - MAXXI 283 LAJEADO/RS - LIMP","10001 - MAXXI 283 LAJEADO/RS - MANUT","10001 - MAXXI 283 LAJEADO/RS - SEG","10001 - MAXXI 285 - LIMPEZA",
                "10001 - MAXXI 285 - SEG","10001 - MAXXI 285 - SEG","10001 - MAXXI 285 - SEG","10001 - MAXXI 285 FAZENDINHA (PR)",
                "10001 - MAXXI 311 GUARAPUAVA (PR)","10001 - MAXXI 311 GUARAPUAVA - LIMP","10001 - MAXXI 311 GUARAPUAVA - MANUT",
                "10001 - MAXXI 311 GUARAPUAVA - SEG","10001 - MAXXI 318 SANTO ANGELO (RS)","10001 - MAXXI 318 SANTO ANGELO - LIMP",
                "10001 - MAXXI 318 SANTO ANGELO - SEG","10001 - MAXXI 319 ITABUNA BA","10001 - MAXXI 319 ITABUNA BA-SEG","10001 - MAXXI 321 ERECHIM/RS",
                "10001 - MAXXI 337 TERESINA PI","10001 - MAXXI 337 TERESINA PI - LIMP","10001 - MAXXI 337 TERESINA PI - SEG","10001 - MAXXI 338 PARNAMIRIM RN",
                "10001 - MAXXI 338 PARNAMIRIM RN - LIMP","10001 - MAXXI 338 PARNAMIRIM RN - SEG","10001 - MAXXI 359 PIRACICABA",
                "10001 - MAXXI 359 PIRACICABA - LIMP","10001 - MAXXI 359 PIRACICABA - SEG","10001 - MAXXI 363 SANTA BARBARA",
                "10001 - MAXXI 363 SANTA BARBARA LIMP","10001 - MAXXI 363 SANTA BARBARA SEG","10001 - MAXXI 365 RIBEIRAO NEVES",
                "10001 - MAXXI 365 RIBEIRAO NEVES-SEG","10001 - MAXXI 369 MOSSORO-RN","10001 - MAXXI 369 MOSSORO-RN / LIMPEZA",
                "10001 - MAXXI 369 MOSSORO-RN / SEG","10001 - MAXXI 370 PRES. PRUDENTE","10001 - MAXXI 370 PRES. PRUDENTE-LIMPE",
                "10001 - MAXXI 370 PRES. PRUDENTE-SEG","10001 - MAXXI BOQUEIRAO","10001 - MAXXI BOQUEIRAO","10001 - MAXXI BOQUEIRAO-LIMP",
                "10001 - MAXXI BOQUEIRAO-SEG","10001 - MAXXI CABO SANTO AGOSTINHO LIM","10001 - MAXXI CABO SANTO AGOSTINHO SEG",
                "10001 - MAXXI CABO SANTO DE AGOSTINHO","10001 - MAXXI CABO SANTO DE AGOSTINHO","10001 - MAXXI CAMPO GRANDE",
                "10001 - MAXXI CAMPO GRANDE - LIMP","10001 - MAXXI CAMPO GRANDE - SEG","10001 - MAXXI CAMPO GRANDE SUL LIMP",
                "10001 - MAXXI CAMPO GRANDE SUL SEG","10001 - MAXXI CANOAS","10001 - MAXXI CANOAS-LIMP","10001 - MAXXI CANOAS-SEG","10001 - MAXXI DIADEMA","10001 - MAXXI DIADEMA - FARM","10001 - MAXXI DIADEMA - LIMP","10001 - MAXXI DIADEMA - SEG","10001 - MAXXI DIRECAO","10001 - MAXXI DIRECAO","10001 - MAXXI DISTRIBUICAO POA","10001 - MAXXI DISTRIBUIDOR BAHIA (ADM)","10001 - MAXXI DISTRIBUIDOR RECIFE","10001 - MAXXI DISTRIBUIDOR RECIFE","10001 - MAXXI DISTRIBUIDOR SAO PAULO","10001 - MAXXI DISTRIBUIDOR SC (ADM)","10001 - MAXXI FEIRA DE SANTANA - LIMP","10001 - MAXXI FEIRA DE SANTANA - SEG","10001 - MAXXI FEIRA DE SANTANA BA","10001 - MAXXI FLORIANOPOLIS","10001 - MAXXI FLORIANOPOLIS-LIMP","10001 - MAXXI FLORIANOPOLIS-SEG","10001 - MAXXI GRAVATAI","10001 - MAXXI GRAVATAI-LIMP","10001 - MAXXI GRAVATAI-SEG","10001 - MAXXI HUMAITA","10001 - MAXXI HUMAITA-SEG","10001 - MAXXI ITAJAI","10001 - MAXXI ITAJAI - LIMP","10001 - MAXXI ITAJAI - SEG","10001 - MAXXI ITAJAI- FARM","10001 - MAXXI JARDIM AMERICA","10001 - MAXXI JOINVILLE","10001 - MAXXI JUAZEIRO DO NORTE","10001 - MAXXI JUAZEIRO DO NORTE-SEG","10001 - MAXXI MARAPONGA","10001 - MAXXI MARAPONGA","10001 - MAXXI MARAPONGA - LIMP","10001 - MAXXI MARAPONGA - SEG","10001 - MAXXI MARAPONGA - SEG","10001 - MAXXI MARAPONGA - SEG","10001 - MAXXI MARES","10001 - MAXXI MARES - LIMP","10001 - MAXXI MARES - MANUT","10001 - MAXXI MARES - SEG","10001 - MAXXI MARILIA - FARM","10001 - MAXXI NOVO HAMBURGO","10001 - MAXXI NOVO HAMBURGO - SEG","10001 - MAXXI NOVO HAMBURGO- LIMP","10001 - MAXXI PAU DA LIMA","10001 - MAXXI PAU DA LIMA - FARM","10001 - MAXXI PAU DA LIMA - LIMP","10001 - MAXXI PAU DA LIMA - SEG","10001 - MAXXI PELOTAS","10001 - MAXXI PELOTAS - LIMP","10001 - MAXXI PELOTAS - SEG","10001 - MAXXI RIO CLARO","10001 - MAXXI RIO GRANDE","10001 - MAXXI RIO GRANDE-LIMP","10001 - MAXXI RIO GRANDE-SEG","10001 - MAXXI SANTA MARIA","10001 - MAXXI SANTA MARIA-LIMP","10001 - MAXXI SANTA MARIA-MANUT","10001 - MAXXI SANTA MARIA-SEG","10001 - MAXXI SAO JOSE CAXIAS","10001 - MAXXI SAO JOSE CAXIAS-LIMP","10001 - MAXXI SAO JOSE CAXIAS-SEG","10001 - MAXXI SARANDI","10001 - MAXXI SARANDI-LIMP","10001 - MAXXI SARANDI-MANUT","10001 - MAXXI SARANDI-SEG","10001 - MAXXI ST CRUZ BR 471","10001 - MAXXI ST CRUZ BR 471-LIMP","10001 - MAXXI ST CRUZ BR 471-SEG","10001 - MAXXI VALPARAISO DE GOIAS","10001 - MAXXI VALPARAISO DE GOIAS LIMP","10001 - MAXXI VALPARAISO DE GOIAS SEG","10001 - MAXXI VITORIA DA CONQUISTA LIM","10001 - MAXXI VITORIA DA CONQUISTA SEG","10001 - MERC ALTO DA XV","10001 - MERC ALTO DA XV-LIMP","10001 - MERC ALTO DA XV-SEG","10001 - MERC BACACHERI 2","10001 - MERC BACACHERI 2","10001 - MERC BACACHERI 2-LIMP","10001 - MERC BACACHERI 2-PROM","10001 - MERC BACACHERI 2-SEG","10001 - MERC BATEL","10001 - MERC BATEL-LIMP","10001 - MERC BATEL-SEG","10001 - MERC BIGORRILHO","10001 - MERC BIGORRILHO-LIMP","10001 - MERC BIGORRILHO-SEG","10001 - MERC CABRAL","10001 - MERC CABRAL-LIMP","10001 - MERC CABRAL-SEG","10001 - MERC CENTRO CIVICO","10001 - MERC CENTRO CIVICO-LIMP","10001 - MERC CENTRO CIVICO-SEG","10001 - MERC COM ARAUJO","10001 - MERC COM ARAUJO-LIMP","10001 - MERC COM ARAUJO-SEG","10001 - MERC GEN. OSORIO","10001 - MERC GEN. OSORIO-LIMP","10001 - MERC GEN. OSORIO-SEG","10001 - MERC JARDIM AMERICAS 10","10001 - MERC JARDIM AMERICAS 10-LIMP","10001 - MERC JARDIM AMERICAS 10-SEG","10001 - MERC JUVEVE","10001 - MERC JUVEVE-LIMP","10001 - MERC JUVEVE-SEG","10001 - MERC LONDRINA JK","10001 - MERC LONDRINA JK-LIMP","10001 - MERC LONDRINA JK-SEG","10001 - MERC MARINGA","10001 - MERC MARINGA-LIMP","10001 - MERC MARINGA-SEG","10001 - MERC NOVO MUNDO","10001 - MERC NOVO MUNDO-LIMP","10001 - MERC NOVO MUNDO-SEG","10001 - MERC REBOUCAS","10001 - MERC REBOUCAS","10001 - MERC REBOUCAS-LIMP","10001 - MERC REBOUCAS-SEG","10001 - MERC SAO JOSE PINHAIS","10001 - MERC SAO JOSE PINHAIS-LIMP","10001 - MERC SAO JOSE PINHAIS-SEG","10001 - MERC SAO LOURENCO","10001 - MERC SAO LOURENCO-LIMP","10001 - MERC SAO LOURENCO-SEG","10001 - MERC SEMINARIO","10001 - MERC SEMINARIO-LIMP","10001 - MERC SEMINARIO-SEG","10001 - MERC SILVA JARDIM","10001 - MERC SILVA JARDIM","10001 - MERC TIRADENTES 220","10001 - MERC TIRADENTES 321","10001 - MERC TIRADENTES 321-LIMP","10001 - MERC TIRADENTES 321-SEG","10001 - MERC UMUARAMA","10001 - MERC UMUARAMA-LIMP","10001 - MERC UMUARAMA-SEG","10001 - MERC XV NOVEMBRO","10001 - MERC XV NOVEMBRO-LIMP","10001 - MERC XV NOVEMBRO-SEG","10001 - MERCEARIA","10001 - NAC ALEGRETE-LIMP","10001 - NAC ALEGRETE-SEG","10001 - NAC ALVORADA GET VARGAS","10001 - NAC BAGE TUPY SILV","10001 - NAC BAGE TUPY SILV-LIMP","10001 - NAC BAGE TUPY SILV-SEG","10001 - NAC BARAO AZEVEDO","10001 - NAC BARAO AZEVEDO","10001 - NAC BARAO AZEVEDO-LIMP","10001 - NAC BARAO AZEVEDO-SEG","10001 - NAC BARRA RIBEIRO","10001 - NAC BARRA RIBEIRO-LIMP","10001 - NAC BARRA RIBEIRO-SEG","10001 - NAC BELA VISTA POA","10001 - NAC BELA VISTA POA","10001 - NAC BELA VISTA POA- CAFETERIA","10001 - NAC BELA VISTA POA-SEG","10001 - NAC CACH F CUNHA","10001 - NAC CACH F CUNHA-LIMP","10001 - NAC CACH F CUNHA-SEG","10001 - NAC CAMAQUA","10001 - NAC CAMAQUA - LIMP","10001 - NAC CAMAQUA-SEG","10001 - NAC CANOAS G VARGAS","10001 - NAC CANOAS G VARGAS-LIMP","10001 - NAC CANOAS G VARGAS-SEG","10001 - NAC CANOAS J CASTILHO","10001 - NAC CANOAS J CASTILHO-LIMP","10001 - NAC CANOAS J CASTILHO-SEG","10001 - NAC CAPAO DA CANOA","10001 - NAC CAPAO DA CANOA- LIMP","10001 - NAC CAPAO DA CANOA-SEG","10001 - NAC CAXIAS 20 SETEMBRO-LJ FECH","10001 - NAC CAXIAS RIO BRANCO-LIMP","10001 - NAC CAXIAS SAO PELEG","10001 - NAC CIDADE BAIXA","10001 - NAC CIDADE BAIXA-PROM","10001 - NAC CIDADE BAIXA-SEG","10001 - NAC CRUZ ALTA","10001 - NAC CRUZ ALTA-LIMP","10001 - NAC CRUZ ALTA-SEG","10001 - NAC DOM PEDRITO","10001 - NAC DOM PEDRITO-LIMP","10001 - NAC DOM PEDRITO-SEG","10001 - NAC ESTEIO 24 AGOSTO","10001 - NAC ESTEIO 24 AGOSTO-LIMP","10001 - NAC ESTEIO 24 AGOSTO-SEG","10001 - NAC ESTEIO J MACHADO","10001 - NAC ESTEIO V OLIMPICA","10001 - NAC ESTEIO V OLIMPICA-LIMP","10001 - NAC ESTEIO V OLIMPICA-SEG","10001 - NAC FLORIANOPOLIS","10001 - NAC FLORIANOPOLIS - LIMP","10001 - NAC FLORIANOPOLIS - SEG","10001 - NAC GRAMADO","10001 - NAC GRAMADO - CAFETERIA","10001 - NAC GRAMADO-SEG","10001 - NAC GRAV D OLIVEIRA","10001 - NAC GRAV VILA BRANCA","10001 - NAC GRAV VILA BRANCA-LIMP","10001 - NAC GRAV VILA BRANCA-SEG","10001 - NAC GRAVATAI","10001 - NAC GRAVATAI - RESTAURANTE","10001 - NAC GRAVATAI- LIMP","10001 - NAC GRAVATAI-SEG","10001 - NAC GUAIBA 20 SETEMBRO","10001 - NAC GUAIBA 20 SETEMBRO-LIMP","10001 - NAC GUAIBA 20 SETEMBRO-SEG","10001 - NAC GUAIBA B SCHELL","10001 - NAC GUAIBA B SCHELL-LIMP","10001 - NAC GUAIBA B SCHELL-SEG","10001 - NAC HAMB VELHO","10001 - NAC HAMB VELHO-LIMP","10001 - NAC HAMB VELHO-SEG","10001 - NAC IGUATEMI","10001 - NAC IGUATEMI - CAFETERIA","10001 - NAC IGUATEMI - RESTAURANTE","10001 - NAC IGUATEMI-SEG","10001 - NAC IJUI JOAO BONIFACIO","10001 - NAC IJUI JOAO BONIFACIO - REST","10001 - NAC IJUI JOAO BONIFACIO-LIMP","10001 - NAC IJUI JOAO BONIFACIO-SEG","10001 - NAC LINDOIA","10001 - NAC LINDOIA-SEG","10001 - NAC LUCAS OLIVEIRA-SEG","10001 - NAC MENINO DEUS","10001 - NAC MENINO DEUS-LIMP","10001 - NAC MENINO DEUS-SEG","10001 - NAC MIGUEL TOSTES","10001 - NAC MIGUEL TOSTES-SEG","10001 - NAC MIGUEL TOSTES-SEG","10001 - NAC MONTENEGRO O ARANHA","10001 - NAC MONTENEGRO O ARANHA-LIMP","10001 - NAC MONTENEGRO O ARANHA-SEG","10001 - NAC NOVO HAMB GOMES PORT","10001 - NAC NOVO HAMB GOMES PORT-LIMP","10001 - NAC NOVO HAMB GOMES PORT-SEG","10001 - NAC NOVO HAMB SHOPPING","10001 - NAC OBIRICI","10001 - NAC OBIRICI-SEG","10001 - NAC OSORIO BR 101","10001 - NAC OSORIO BR 101-LIMP","10001 - NAC OSORIO BR 101-SEG","10001 - NAC PELOTAS G CHAVES-LIMP","10001 - NAC PELOTAS G. CHAVES","10001 - NAC PELOTAS G. CHAVES-SEG","10001 - NAC PELOTAS GEN OSORIO","10001 - NAC PELOTAS GEN OSORIO","10001 - NAC PELOTAS GEN OSORIO-LIMP","10001 - NAC PELOTAS GEN OSORIO-SEG","10001 - NAC PELOTAS LOBO COSTA","10001 - NAC PELOTAS LOBO COSTA-LIMP","10001 - NAC PELOTAS LOBO COSTA-SEG","10001 - NAC POA CRISTO RED","10001 - NAC POA CRISTO RED-LIMP","10001 - NAC POA CRISTO RED-SEG","10001 - NAC POA GOMES FREITA","10001 - NAC POA GOMES FREITA-LIMP","10001 - NAC POA GOMES FREITA-SEG","10001 - NAC POA JD LEOPOLDINA","10001 - NAC POA JD LEOPOLDINA-LIMP","10001 - NAC POA JD LEOPOLDINA-SEG","10001 - NAC POA JD LEOPOLDINA-SEG","10001 - NAC POA PROTASIO","10001 - NAC POA PROTASIO-LIMP","10001 - NAC POA PROTASIO-SEG","10001 - NAC POA REPUBLICA","10001 - NAC POA SANTANA","10001 - NAC POA SANTANA","10001 - NAC POA SANTANA","10001 - NAC POA SANTANA-LIMP","10001 - NAC POA SANTANA-SEG","10001 - NAC POA VENAN AIRES","10001 - NAC POA VENAN AIRES","10001 - NAC POA VENAN AIRES-LIMP","10001 - NAC POA VENAN AIRES-SEG","10001 - NAC POA WESCESLAU","10001 - NAC POA WESCESLAU - ON LINE","10001 - NAC POA WESCESLAU - REST","10001 - NAC POA WESCESLAU-LIMP","10001 - NAC POA WESCESLAU-SEG","10001 - NAC PRAIA DE BELAS","10001 - NAC PRAIA DE BELAS-LIMP","10001 - NAC PRAIA DE BELAS-ON LINE","10001 - NAC PRAIA DE BELAS-SEG","10001 - NAC RIO GRANDE CASSINO","10001 - NAC RIO GRANDE CASSINO-LIMP","10001 - NAC RIO GRANDE CASSINO-SEG","10001 - NAC ROSARIO CERRO","10001 - NAC ROSARIO CERRO-LIMP","10001 - NAC ROSARIO CERRO-SEG","10001 - NAC RUA DA PRAIA","10001 - NAC RUA DA PRAIA","10001 - NAC RUA DA PRAIA-LIMP","10001 - NAC RUA DA PRAIA-SEG","10001 - NAC SANTA CRUZ CEL BRITO","10001 - NAC SANTA CRUZ CEL BRITO-LIMP","10001 - NAC SANTA CRUZ CEL BRITO-SEG","10001 - NAC SANTA ROSA","10001 - NAC SANTA ROSA - RESTAURANTE","10001 - NAC SANTA ROSA-LIMP","10001 - NAC SANTA ROSA-SEG","10001 - NAC SAO BORJA RIACH","10001 - NAC SAO BORJA S DORN","10001 - NAC SAO BORJA S DORN-LIMP","10001 - NAC SAO BORJA S DORN-SEG","10001 - NAC SAO GABRIEL","10001 - NAC SAO GABRIEL-LIMP","10001 - NAC SAO GABRIEL-SEG","10001 - NAC SAO LEOP CRISTO REI-LIMP","10001 - NAC SAO LEOP CRISTO REI-SEG","10001 - NAC SAO LEOP FEITORIA","10001 - NAC SAO LEOP SAO JOAQUIM","10001 - NAC SAO LEOP SAO JOAQUIM-LIMP","10001 - NAC SAO LEOP SAO JOAQUIM-SEG","10001 - NAC SAPUCAIA CENTRO","10001 - NAC SAPUCAIA CENTRO-LIMP","10001 - NAC SAPUCAIA CENTRO-SEG","10001 - NAC ST MARIA A AZEVEDO","10001 - NAC ST MARIA A AZEVEDO-LIMP","10001 - NAC ST MARIA A AZEVEDO-SEG","10001 - NAC ST MARIA MEDIANEIRA","10001 - NAC ST MARIA MEDIANEIRA-CAFE","10001 - NAC ST MARIA MEDIANEIRA-LIMP","10001 - NAC ST MARIA MEDIANEIRA-SEG","10001 - NAC STO ANGELO","10001 - NAC STO ANGELO - CAFETERIA","10001 - NAC STO ANGELO-LIMP","10001 - NAC STO ANGELO-SEG","10001 - NAC STO ANTONIO PAT","10001 - NAC STO ANTONIO PAT-LIMP","10001 - NAC STO ANTONIO PAT-SEG","10001 - NAC TAQUARA RONDA","10001 - NAC TAQUARA RONDA-1º EMP","10001 - NAC TAQUARA RONDA-LIMP","10001 - NAC TAQUARA RONDA-SEG","10001 - NAC TERESOPOLIS","10001 - NAC TERESOPOLIS-SEG","10001 - NAC TORRES","10001 - NAC TORRES- LIMP","10001 - NAC TORRES-SEG","10001 - NAC TRAMANDAI","10001 - NAC TRAMANDAI - LIMP","10001 - NAC TRAMANDAI-SEG","10001 - NAC TRISTEZA","10001 - NAC VIAMAO A VESPUCIO","10001 - NAC VIAMAO A VESPUCIO-SEG","10001 - NAC XANGRILA","10001 - NAC XANGRILA - LIMP","10001 - NAC XANGRILA-CAFETERIA","10001 - NAC XANGRILA-SEG","10001 - NACIONAL 219 CAXIAS DO SUL/RS","10001 - NACIONAL 219 CAXIAS DO SUL/RS","10001 - NACIONAL BENTO GONCALVES","10001 - NACIONAL BENTO GONCALVES - SEG","10001 - NACIONAL BENTO GONCALVES-LIMP","10001 - NACIONAL BOA VISTA","10001 - NACIONAL BOA VISTA - SEG","10001 - NACIONAL IMBE","10001 - NACIONAL IMBE - CAFETERIA","10001 - NACIONAL IMBE - LIMP","10001 - NACIONAL IMBE - SEG","10001 - NACIONAL TUBARAO","10001 - NACIONAL TUBARAO - LIMP","10001 - NACIONAL TUBARAO - SEG","10001 - NOVAS LOJAS","10001 - OPER ESTRUT SUL","10001 - OPER HIPER SUL","10001 - OPER MAXXI","10001 - OPER SUPER SUL","10001 - OPER TODO DIA","10001 - OPERACOES CH","10001 - OPERACOES PR","10001 - PADARIA CIDADE BAIXA","10001 - PADARIA ROSARIO","10001 - PERECIVEIS - PR","10001 - PERECIVEIS - SUL","10001 - POSTO 940 CONTAGEM","10001 - POSTO 941 HTD PAULISTA - PE","10001 - POSTO 944 NOVO HAMBURGO/RS","10001 - POSTO 947 CAMPO MOURAO","10001 - POSTO COMBUST - BIG ARARAS","10001 - POSTO COMBUST - BIG CAMBORIU","10001 - POSTO COMBUST - BIG GRAVATAI","10001 - POSTO COMBUST - BIG LIMEIRA","10001 - POSTO COMBUST - BIG PIRACICABA","10001 - POSTO COMBUST - MAXXI ST MARIA","10001 - POSTO COMBUST - SC BAURU SP","10001 - POSTO COMBUST- SAMS NITEROI RJ","10001 - POSTO COMBUST- SC SB DO CAMPO","10001 - POSTO LINHA AMARELA 915 / RJ","10001 - PRICING","10001 - PRICING","10001 - PRICING","10001 - PRICING - MAXXI ATACADO","10001 - PRICING - MAXXI ATACADO","10001 - PRICING - MAXXI ATACADO","10001 - PRICING - PESQUISADORES SUL","10001 - PRICING - PESQUISADORES SUL","10001 - PRICING - PESQUISADORES SUL","10001 - PRICING - PESQUISADORES SUL","10001 - PRICING - PESQUISADORES SUL","10001 - PRICING - PESQUISADORES SUL","10001 - PRICING - PESQUISADORES SUL","10001 - PRICING - PESQUISADORES SUL","10001 - PRICING - PESQUISADORES SUL","10001 - PRICING - PESQUISADORES SUL","10001 - PRICING - PESQUISADORES SUL","10001 - REC HUMANOS - TRAINEE SUL","10001 - REC HUMANOS - TRAINEE SUL","10001 - RELACOES GOVERNAMENTAIS","10001 - RH - TRAINEE CENTRO SUL","10001 - RH - TRAINEE CENTRO SUL","10001 - SAC","10001 - SDB DISTRIBUICAO CANOAS","10001 - SEGURANCA ALIMENTAR","10001 - TODO DIA 279 CAMPO BOM","10001 - TODO DIA 279 CAMPO BOM - FARM","10001 - TODO DIA 279 CAMPO BOM - SEG","10001 - TODO DIA 290 ESTANCIA VELHA","10001 - TODO DIA 293 TAQUARA/RS C1318","10001 - TODO DIA 304 ALVORADA","10001 - TODO DIA 304 ALVORADA - SEG","10001 - TODO DIA 306 LAPA/PR","10001 - TODO DIA 306 LAPA/PR  - SEG","10001 - TODO DIA 306 LAPA/PR - LIMP","10001 - TODO DIA 314 SAO LEOPOLDO RS","10001 - TODO DIA 314 SAO LEOPOLDO SEG","10001 - TODO DIA 317 PARANAGUA/PR","10001 - TODO DIA 317 PARANAGUA/PR LIMP","10001 - TODO DIA 317 PARANAGUA/PR SEG","10001 - TODO DIA 326 RIO PARDO","10001 - TODO DIA 326 RIO PARDO - SEG","10001 - TODO DIA 327 PARANAGUA","10001 - TODO DIA 327 PARANAGUA-SEG","10001 - TODO DIA 329 ARAUCARIA","10001 - TODO DIA 329 ARAUCARIA - LIMP","10001 - TODO DIA 329 ARAUCARIA - SEG","10001 - TODO DIA 332 SAPUCAIA DO SUL","10001 - TODO DIA 332 SAPUCAIA SUL SEG","10001 - TODO DIA 333 PAROBE RS","10001 - TODO DIA 333 PAROBE RS - SEG","10001 - TODO DIA 343 ERNESTO VILEL LIM","10001 - TODO DIA 343 ERNESTO VILEL SEG","10001 - TODO DIA 343 ERNESTO VILELA","10001 - TODO DIA 345 PONTA GROSSA","10001 - TODO DIA 345 PONTA GROSSA LIMP","10001 - TODO DIA 345 PONTA GROSSA SEG","10001 - TODO DIA 346 S.JOSE PINHAIS","10001 - TODO DIA 346 SJOSE PINHAIS LIM","10001 - TODO DIA 346 SJOSE PINHAIS SEG","10001 - TODO DIA 351 PARANAGUAMIRIM","10001 - TODO DIA 351 PARANAGUAMIRIMLIM","10001 - TODO DIA 351 PARANAGUAMIRIMSEG","10001 - TODO DIA 352 PIRAQUARA","10001 - TODO DIA 352 PIRAQUARA LIMP","10001 - TODO DIA 352 PIRAQUARA SEG","10001 - TODO DIA 353 IRIRIU","10001 - TODO DIA 353 IRIRIU - SEG","10001 - TODO DIA 357 CANOAS RIO B-SEG","10001 - TODO DIA 357 CANOAS RIO BRANCO","10001 - TODO DIA 358 VIAMAO","10001 - TODO DIA 358 VIAMAO - SEG","10001 - TODO DIA 360 S MATEUS-LIMP","10001 - TODO DIA 360 SAO MATEUS DO SUL","10001 - TODO DIA 360 SAO MATEUS DO SUL","10001 - TODO DIA 379 BOEHMERWALD","10001 - TODO DIA 379 BOEHMERWALD - SEG","10001 - TODO DIA 379 BOEHMERWALD -LIMP","10001 - TODO DIA 381 CASTRO","10001 - TODO DIA 381 CASTRO SEG","10001 - TODO DIA ALTO DO BOQUEIRAO","10001 - TODO DIA ALTO DO BOQUEIRAO LIM","10001 - TODO DIA ALTO DO BOQUEIRAO SEG","10001 - TODO DIA C. E SILVA JOINVILLE","10001 - TODO DIA C.SILVA JOINVILLE LIM","10001 - TODO DIA C.SILVA JOINVILLE SEG","10001 - TODO DIA CANOAS G SCHELL","10001 - TODO DIA CANOAS G SCHELL-SEG","10001 - TODO DIA CANUDOS I","10001 - TODO DIA CANUDOS I - SEG","10001 - TODO DIA CANUDOS II","10001 - TODO DIA CANUDOS II - SEG","10001 - TODO DIA COMASA JOINVILLE","10001 - TODO DIA COMASA JOINVILLE LIMP","10001 - TODO DIA COMASA JOINVILLE SEG","10001 - TODO DIA COMERCIAL","10001 - TODO DIA E PERNETA PINHAIS","10001 - TODO DIA E PERNETA PINHAIS-LIM","10001 - TODO DIA E PERNETA PINHAIS-SEG","10001 - TODO DIA ESTANCIA VELHA - FARM","10001 - TODO DIA ESTANCIA VELHA - SEG","10001 - TODO DIA IGREJINHA","10001 - TODO DIA IGREJINHA - SEG","10001 - TODO DIA PASQUALINI SAPUC-SEG","10001 - TODO DIA PASQUALINI SAPUCAIA","10001 - TODO DIA PINHAIS","10001 - TODO DIA PINHAIS","10001 - TODO DIA PINHAIS - LIMP","10001 - TODO DIA PROTASIO ALVES","10001 - TODO DIA PROTASIO ALVES - FARM","10001 - TODO DIA S LEOP CAMPINA SEG","10001 - TODO DIA S LEOPOLDO CAMPINA","10001 - TODO DIA S MATEUS DO SUL - SEG","10001 - TRAINEE ATACADOS","10001 - TRAINEE ATACADOS","10001 - TRAINEE ATACADOS","10001 - TRAINEE TODO DIA",
                "10001 - TRAINEE TODO DIA","10001 - TRANSPORTES PR","10001 - TRANSPORTES RS","10001 - UPSTREAM",
                "10001 - UPSTREAM"
	];
	$("#help_friend" ).autocomplete({
		source: esportes
	});

        $("#form").submit(function () {
            return false;
        });
        $("#envia").click(function () {
            envia_form();
        });
        function envia_form() {
            $("#conteudo_periodico").empty();
            var empresa = $("#empresa").val();
            var estabelecimento = $("#estabelecimento").val();

            if ($("#empresa").val() === '0') {
                $("#empresa_error").html("<div class='alert alert-danger alert-dismissable'><button type='button' class='close' data-dismiss='alert' aria-hidden='true'>×</button>Informe Empresa...</div>").hide(2405),
                        $("#empresa").focus();
                return false;
            } else {
                $("#empresa_error").empty();
            }

            if ($("#estabelecimento").val() === '0' || $("#estabelecimento").val() === 'na') {
                $("#estabelecimento_error").html("<div class='alert alert-danger alert-dismissable'><button type='button' class='close' data-dismiss='alert' aria-hidden='true'>×</button>Informe Loja...</div>").hide(2407),
                        $("#estabelecimento").focus();
                return false;
            } else {
                $("#estabelecimento_error").empty();
            }

            $.ajax({
                type: "POST",
                dataType: "HTML",
                url: "../Controller/wal_listar.php",
                data: "empresa=" + empresa + "&estabelecimento=" + estabelecimento,
                beforeSend: function () {
                    $("#conteudo_periodico").html("<img src='../../images/loading/load.gif' class='img-rounded img-responsive' id='imgpos'>");
                },
                success: function (response) {
                    $("#conteudo_periodico").html(response),
                            $('#button').css("display", "block").show(1090),
                            $('#datadoperiodico').css("display", "block").show(1090);
                },
                error: function () {
                    alert("Ocorreu um erro durante a requisição");
                }
            });
        }
    });
</script>
<script>
    $(document).ready(function () {
        $("#button").click(function () {
            envia_array();
        });
        function envia_array() {
            var favorite = [];
            $.each($("input[name='matricula']:checked"), function () {
                favorite.push($(this).val());
            });
            var errou = [];
            $.each($("input[name='erro']:checked"), function () {
                errou.push($(this).val());
            });

            var erro_identificacao = [];
            $.each($("input[name='erro_identificacao']:checked"), function () {
                erro_identificacao.push($(this).val());
            });

            var erro_riscos = [];
            $.each($("input[name='erro_riscos']:checked"), function () {
                erro_riscos.push($(this).val());
            });

            var erro_data_ASO = [];
            $.each($("input[name='erro_data_ASO']:checked"), function () {
                erro_data_ASO.push($(this).val());
            });

            var erro_data_exames = [];
            $.each($("input[name='erro_data_exames']:checked"), function () {
                erro_data_exames.push($(this).val());
            });

            var erro_assinatura_ativo = [];
            $.each($("input[name='erro_assinatura_ativo']:checked"), function () {
                erro_assinatura_ativo.push($(this).val());
            });

            var erro_assinatura_medico = [];
            $.each($("input[name='erro_assinatura_medico']:checked"), function () {
                erro_assinatura_medico.push($(this).val());
            });

            var erro_carimbo = [];
            $.each($("input[name='erro_carimbo']:checked"), function () {
                erro_carimbo.push($(this).val());
            });

            var erro_rasuras = [];
            $.each($("input[name='erro_rasuras']:checked"), function () {
                erro_rasuras.push($(this).val());
            });

            var erro_falta_apto = [];
            $.each($("input[name='erro_falta_apto']:checked"), function () {
                erro_falta_apto.push($(this).val());
            });

            var erro_falta_habilitado = [];
            $.each($("input[name='erro_falta_habilitado']:checked"), function () {
                erro_falta_habilitado.push($(this).val());
            });
            
            var erro_tel = [];
            $.each($("input[name='erro_tel']:checked"), function () {
                erro_tel.push($(this).val());
            });
            
            var erro_coord = [];
            $.each($("input[name='erro_coord']:checked"), function () {
                erro_coord.push($(this).val());
            });
            
            var erro_duplicado = [];
            $.each($("input[name='erro_duplicado']:checked"), function () {
                erro_duplicado.push($(this).val());
            });
            
            var falta_aso = [];
            $.each($("input[name='falta_aso']:checked"), function () {
                falta_aso.push($(this).val());
            });

            var data_periodico = $("#data_periodico").val();
            var id_medico = $("#id_medico").val();
            var id_medico_coordenador = $("#id_medico_coordenador").val();
            var caixa = $("#caixa").val();
            var comp_ACIDO_METIL_HIPURICO = $("#comp_ACIDO_METIL_HIPURICO").val() === '' ? '0000-00-00 00:00:00' : $("#comp_ACIDO_METIL_HIPURICO").val();
            var comp_HEMOGRAMA = $("#comp_HEMOGRAMA").val() === '' ? '0000-00-00 00:00:00' : $("#comp_HEMOGRAMA").val();
            var comp_ACIDO_MANDELICO = $("#comp_ACIDO_MANDELICO").val() === '' ? '0000-00-00 00:00:00' : $("#comp_ACIDO_MANDELICO").val();
            var comp_VDRL = $("#comp_VDRL").val() === '' ? '0000-00-00 00:00:00' : $("#comp_VDRL").val();
            var comp_RETICULOCITOS = $("#comp_RETICULOCITOS").val() === '' ? '0000-00-00 00:00:00' : $("#comp_RETICULOCITOS").val();
            var comp_PARASITOLOGICO_FEZES = $("#comp_PARASITOLOGICO_FEZES").val() === '' ? '0000-00-00 00:00:00' : $("#comp_PARASITOLOGICO_FEZES").val();
            var comp_CULTURAL_DE_OROFARINGE = $("#comp_CULTURAL_DE_OROFARINGE").val() === '' ? '0000-00-00 00:00:00' : $("#comp_CULTURAL_DE_OROFARINGE").val();
            var comp_COPROCULTURA = $("#comp_COPROCULTURA").val() === '' ? '0000-00-00 00:00:00' : $("#comp_COPROCULTURA").val();
            var comp_MICOLOGICO_DE_UNHA = $("#comp_MICOLOGICO_DE_UNHA").val() === '' ? '0000-00-00 00:00:00' : $("#comp_MICOLOGICO_DE_UNHA").val();
            var comp_AUDIOMETRIA = $("#comp_AUDIOMETRIA").val() === '' ? '0000-00-00 00:00:00' : $("#comp_AUDIOMETRIA").val();
            var comp_ECG = $("#comp_ECG").val() === '' ? '0000-00-00 00:00:00' : $("#comp_ECG").val();
            var comp_ACUIDADE_VISUAL = $("#comp_ACUIDADE_VISUAL").val() === '' ? '0000-00-00 00:00:00' : $("#comp_ACUIDADE_VISUAL").val();
            var comp_EEG = $("#comp_EEG").val() === '' ? '0000-00-00 00:00:00' : $("#comp_EEG").val();
            var comp_PLAQUETAS = $("#comp_PLAQUETAS").val() === '' ? '0000-00-00 00:00:00' : $("#comp_PLAQUETAS").val();
            var comp_ERITROGRAMA = $("#comp_ERITROGRAMA").val() === '' ? '0000-00-00 00:00:00' : $("#comp_ERITROGRAMA").val();
            var comp_ACIDO_TT_MUCONICO = $("#comp_ACIDO_TT_MUCONICO").val() === '' ? '0000-00-00 00:00:00' : $("#comp_ACIDO_TT_MUCONICO").val();
            var comp_GLICEMIA_EM_JEJUM = $("#comp_GLICEMIA_EM_JEJUM").val() === '' ? '0000-00-00 00:00:00' : $("#comp_GLICEMIA_EM_JEJUM").val();
            var comp_ACIDO_HIPURICO = $("#comp_ACIDO_HIPURICO").val() === '' ? '0000-00-00 00:00:00' : $("#comp_ACIDO_HIPURICO").val();
            var comp_AVALIACAO_PSICOSSOCIAL = $("#comp_AVALIACAO_PSICOSSOCIAL").val() === '' ? '0000-00-00 00:00:00' : $("#comp_AVALIACAO_PSICOSSOCIAL").val();
            var status_ACIDO_METIL_HIPURICO = $("#status_ACIDO_METIL_HIPURICO").val() === 'na' ? 0 : $("#status_ACIDO_METIL_HIPURICO").val();
            var status_HEMOGRAMA = $("#status_HEMOGRAMA").val() === 'na' ? 0 : $("#status_HEMOGRAMA").val();
            var status_ACIDO_MANDELICO = $("#status_ACIDO_MANDELICO").val() === 'na' ? 0 : $("#status_ACIDO_MANDELICO").val();
            var status_VDRL = $("#status_VDRL").val() === 'na' ? 0 : $("#status_VDRL").val();
            var status_RETICULOCITOS = $("#status_RETICULOCITOS").val() === 'na' ? 0 : $("#status_RETICULOCITOS").val();
            var status_PARASITOLOGICO_FEZES = $("#status_PARASITOLOGICO_FEZES").val() === 'na' ? 0 : $("#status_PARASITOLOGICO_FEZES").val();
            var status_CULTURAL_DE_OROFARINGE = $("#status_CULTURAL_DE_OROFARINGE").val() === 'na' ? 0 : $("#status_CULTURAL_DE_OROFARINGE").val();
            var status_COPROCULTURA = $("#status_COPROCULTURA").val() === 'na' ? 0 : $("#status_COPROCULTURA").val();
            var status_MICOLOGICO_DE_UNHA = $("#status_MICOLOGICO_DE_UNHA").val() === 'na' ? 0 : $("#status_MICOLOGICO_DE_UNHA").val();
            var status_AUDIOMETRIA = $("#status_AUDIOMETRIA").val() === 'na' ? 0 : $("#status_AUDIOMETRIA").val();
            var status_ECG = $("#status_ECG").val() === 'na' ? 0 : $("#status_ECG").val();
            var status_ACUIDADE_VISUAL = $("#status_ACUIDADE_VISUAL").val() === 'na' ? 0 : $("#status_ACUIDADE_VISUAL").val();
            var status_EEG = $("#status_EEG").val() === 'na' ? 0 : $("#status_EEG").val();
            var status_PLAQUETAS = $("#status_PLAQUETAS").val() === 'na' ? 0 : $("#status_PLAQUETAS").val();
            var status_ERITROGRAMA = $("#status_ERITROGRAMA").val() === 'na' ? 0 : $("#status_ERITROGRAMA").val();
            var status_ACIDO_TT_MUCONICO = $("#status_ACIDO_TT_MUCONICO").val() === 'na' ? 0 : $("#status_ACIDO_TT_MUCONICO").val();
            var status_GLICEMIA_EM_JEJUM = $("#status_GLICEMIA_EM_JEJUM").val() === 'na' ? 0 : $("#status_GLICEMIA_EM_JEJUM").val();
            var status_ACIDO_HIPURICO = $("#status_ACIDO_HIPURICO").val() === 'na' ? 0 : $("#status_ACIDO_HIPURICO").val();
            var status_AVALIACAO_PSICOSSOCIAL = $("#status_AVALIACAO_PSICOSSOCIAL").val() === 'na' ? 0 : $("#status_AVALIACAO_PSICOSSOCIAL").val();
            
            if ($("#data_periodico").val() === 'na') {
                $("#caixa_error").html("<div class='alert alert-danger alert-dismissable'><button type='button' class='close' data-dismiss='alert' aria-hidden='true'>×</button>Informe...</div>"),
                        $("#data_periodico").focus();
                return false;
            } else {
                $("#caixa_error").empty();
            }

            if ($("#caixa").val() === 'na') {
                $("#caixa_error").html("<div class='alert alert-danger alert-dismissable'><button type='button' class='close' data-dismiss='alert' aria-hidden='true'>×</button>Informe...</div>"),
                        $("#caixa").focus();
                return false;
            } else {
                $("#caixa_error").empty();
            }
            
            if ($("#id_medico").val() === 'na') {
                $("#caixa_error").html("<div class='alert alert-danger alert-dismissable'><button type='button' class='close' data-dismiss='alert' aria-hidden='true'>×</button>Informe...</div>"),
                        $("#id_medico").focus();
                return false;
            } else {
                $("#caixa_error").empty();
            }
            
            if ($("#id_medico_coordenador").val() === 'na') {
                $("#caixa_error").html("<div class='alert alert-danger alert-dismissable'><button type='button' class='close' data-dismiss='alert' aria-hidden='true'>×</button>Informe...</div>"),
                        $("#id_medico_coordenador").focus();
                return false;
            } else {
                $("#caixa_error").empty();
            }

            $.ajax({
                type: "GET",
                dataType: "HTML",
                url: "../Controller/periodico_realizados.php",
                data: "periodico=" + favorite + "&data_periodico=" + data_periodico + "&erro=" + errou +
                        "&comp_ACIDO_METIL_HIPURICO=" + comp_ACIDO_METIL_HIPURICO + "&comp_HEMOGRAMA=" + comp_HEMOGRAMA
                        + "&comp_ACIDO_MANDELICO=" + comp_ACIDO_MANDELICO + "&comp_VDRL=" + comp_VDRL + "&comp_RETICULOCITOS="
                        + comp_RETICULOCITOS + "&comp_PARASITOLOGICO_FEZES=" + comp_PARASITOLOGICO_FEZES + "&comp_CULTURAL_DE_OROFARINGE="
                        + comp_CULTURAL_DE_OROFARINGE + "&comp_COPROCULTURA=" + comp_COPROCULTURA
                        + "&comp_MICOLOGICO_DE_UNHA=" + comp_MICOLOGICO_DE_UNHA + "&comp_AUDIOMETRIA=" + comp_AUDIOMETRIA +
                        "&comp_ECG=" + comp_ECG + "&comp_ACUIDADE_VISUAL=" + comp_ACUIDADE_VISUAL + "&comp_EEG=" + comp_EEG +
                        "&comp_PLAQUETAS=" + comp_PLAQUETAS + "&comp_ERITROGRAMA=" + comp_ERITROGRAMA
                        + "&comp_ACIDO_TT_MUCONICO=" + comp_ACIDO_TT_MUCONICO + "&comp_GLICEMIA_EM_JEJUM=" + comp_GLICEMIA_EM_JEJUM +
                        "&comp_ACIDO_HIPURICO=" + comp_ACIDO_HIPURICO + "&comp_AVALIACAO_PSICOSSOCIAL=" + comp_AVALIACAO_PSICOSSOCIAL + "&caixa=" + caixa +
                        "&status_ACIDO_METIL_HIPURICO=" + status_ACIDO_METIL_HIPURICO + "&status_HEMOGRAMA=" + status_HEMOGRAMA + "&status_ACIDO_MANDELICO=" + status_ACIDO_MANDELICO + "&status_VDRL=" + status_VDRL + "&status_RETICULOCITOS=" + status_RETICULOCITOS + "&status_PARASITOLOGICO_FEZES=" + status_PARASITOLOGICO_FEZES +
                        "&status_CULTURAL_DE_OROFARINGE=" + status_CULTURAL_DE_OROFARINGE + "&status_COPROCULTURA=" + status_COPROCULTURA + "&status_MICOLOGICO_DE_UNHA=" + status_MICOLOGICO_DE_UNHA +
                        "&status_AUDIOMETRIA=" + status_AUDIOMETRIA + "&status_ECG=" + status_ECG + "&status_ACUIDADE_VISUAL=" + status_ACUIDADE_VISUAL +
                        "&status_EEG=" + status_EEG + "&status_PLAQUETAS=" + status_PLAQUETAS + "&status_ERITROGRAMA=" + status_ERITROGRAMA +
                        "&status_ACIDO_TT_MUCONICO=" + status_ACIDO_TT_MUCONICO + "&status_GLICEMIA_EM_JEJUM=" + status_GLICEMIA_EM_JEJUM +
                        "&status_ACIDO_HIPURICO=" + status_ACIDO_HIPURICO + "&status_AVALIACAO_PSICOSSOCIAL=" + status_AVALIACAO_PSICOSSOCIAL +
                        "&erro_identificacao=" + erro_identificacao + "&erro_riscos=" + erro_riscos +
                        "&erro_data_ASO=" + erro_data_ASO + "&erro_data_exames=" + erro_data_exames +
                        "&erro_assinatura_ativo=" + erro_assinatura_ativo + "&erro_assinatura_medico=" + erro_assinatura_medico +
                        "&erro_carimbo=" + erro_carimbo + "&erro_rasuras=" + erro_rasuras +
                        "&erro_falta_apto=" + erro_falta_apto + "&erro_falta_habilitado=" + erro_falta_habilitado + "&id_medico=" + id_medico + "&id_medico_coordenador=" + id_medico_coordenador + 
                        "&erro_tel=" + erro_tel + "&erro_coord=" + erro_coord + "&erro_duplicado=" + erro_duplicado + "&falta_aso=" + falta_aso,
                beforeSend: function () {
                    $("#periodico").html("<img src='../../images/loading/load.gif' class='img-rounded img-responsive'>");
                },
                success: function (response) {
                    $("#periodico").html(response),
                            $("#data_periodico").val(''),
                            $("#caixa").val(''),
                            $("#comp_ACIDO_METIL_HIPURICO").val(''),
                            $("#comp_HEMOGRAMA").val(''),
                            $("#comp_ACIDO_MANDELICO").val(''),
                            $("#comp_VDRL").val(''),
                            $("#comp_RETICULOCITOS").val(''),
                            $("#comp_PARASITOLOGICO_FEZES").val(''),
                            $("#comp_CULTURAL_DE_OROFARINGE").val(''),
                            $("#comp_COPROCULTURA").val(''),
                            $("#comp_MICOLOGICO_DE_UNHA").val(''),
                            $("#comp_AUDIOMETRIA").val(''),
                            $("#comp_ECG").val(''),
                            $("#comp_ACUIDADE_VISUAL").val(''),
                            $("#comp_EEG").val(''),
                            $("#comp_PLAQUETAS").val(''),
                            $("#comp_ERITROGRAMA").val(''),
                            $("#comp_ACIDO_TT_MUCONICO").val(''),
                            $("#comp_GLICEMIA_EM_JEJUM").val(''),
                            $("#comp_ACIDO_HIPURICO").val(''),
                            $("#comp_AVALIACAO_PSICOSSOCIAL").val(''),                            
                            $("#status_ACIDO_METIL_HIPURICO").val('na'),
                            $("#status_HEMOGRAMA").val('na'),
                            $("#status_ACIDO_MANDELICO").val('na'),
                            $("#status_VDRL").val('na'),
                            $("#status_RETICULOCITOS").val('na'),
                            $("#status_PARASITOLOGICO_FEZES").val('na'),
                            $("#status_CULTURAL_DE_OROFARINGE").val('na'),
                            $("#status_COPROCULTURA").val('na'),
                            $("#status_MICOLOGICO_DE_UNHA").val('na'),
                            $("#status_AUDIOMETRIA").val('na'),
                            $("#status_ECG").val('na'),
                            $("#status_ACUIDADE_VISUAL").val('na'),
                            $("#status_EEG").val('na'),
                            $("#status_PLAQUETAS").val('na'),
                            $("#status_ERITROGRAMA").val('na'),
                            $("#status_ACIDO_TT_MUCONICO").val('na'),
                            $("#status_GLICEMIA_EM_JEJUM").val('na'),
                            $("#status_ACIDO_HIPURICO").val('na'),
                            $("#status_AVALIACAO_PSICOSSOCIAL").val('na');                            
                },
                error: function () {
                    alert("Ocorreu um erro durante a requisição");
                }
            });
        }
    });
</script>
<style type="text/css">
    #imgpos {
        position:absolute;
        left:667px;
    }
</style>
<div class="widget">
    <div class="widget-header transparent">
        <h2><strong>Listar Funcionários</strong> <acronym title="Informe os campos para otimizar o resultado!!!">Walmart</acronym></h2>
        <div class="additional-btn">            
            <a href="#" class="widget-toggle"><i class="icon-down-open-2"></i></a>            
        </div>
    </div>
    <div class="widget-content padding">
        <div class="form-inline">
            <form id="form" method="POST">
                <div class="form-group">
                    <label for="empresa_label">Ajuda:</label>
                    <input class="form-control" id="help_friend" name="help_friend">
                </div>
                <div class="form-group">
                    <label for="empresa_label">Empresa:</label>
                    <select class="form-control" id="empresa" name="empresa" required autofocus>
                        <option selected value="0">
                            Selecione...
                        </option>
                        <?php
                        include '../config/database_mysql.php';
                        $pdo = Database::connect();
                        $sql = "SELECT cod_empresa, concat(cod_empresa,' - ',desc_empresa) as desc_empresas FROM wal_empresa ORDER BY desc_empresa ASC";
                        foreach ($pdo->query($sql) as $value) {
                            echo '<option value="' . $value['cod_empresa'] . '">' . $value['desc_empresas'] . '</option>';
                        }
                        ?>
                    </select>
                    <div class="form-inline" id="empresa_error"></div>
                </div>
                <div class="form-group">
                    <label for="estabelecimento_label">Estabelecimento:</label>
                    <select class="form-control" id="estabelecimento" name="estabelecimento" required>
                        <option selected value="na">
                            Aguardando...
                        </option>
                    </select>
                    <div class="form-inline" id="estabelecimento_error"></div>
                </div>
                <button class="btn btn-primary" id="envia" type="submit">Gerar Lista de Ativos</button>                
            </form>
        </div>
    </div>    
    <div class="widget-content padding" id="conteudo_periodico"></div>
    <div class="widget-content padding">
        <div id="datadoperiodico">
            <div class="form-group">
                <label for="estabelecimento_label">Data do Exame Clínico:</label>
                <input type="date" class="form-inline" id="data_periodico" name="data_periodico">
                <label for="estabelecimento_label">Caixa:</label>                        
                <select class="form-inline" id="caixa" name="caixa" required>
                    <option selected value="na">
                        Selecione...
                    </option>
                    <?php
                    $sql1 = "select id, etiqueta from wal_caixa where id_wal_box in (1) and status in (1) order by etiqueta asc";
                    foreach ($pdo->query($sql1) as $value) {
                        echo '<option value="' . $value['id'] . '">' . $value['etiqueta'] . '</option>';
                    }
                    ?>
                </select>
                <div class="form-group">
                    <label for="estabelecimento_label">Médico:</label>                        
                    <select class="form-inline" id="id_medico" name="id_medico" required>
                        <option selected value="na">
                            Selecione...
                        </option>
                        <?php
                        $sqlmedico = "select id, nome_extenso from usuarios where setor in (28) and status in (1) order by nome asc";
                        foreach ($pdo->query($sqlmedico) as $value) {
                            echo '<option value="' . $value['id'] . '">' . $value['nome_extenso'] . '</option>';
                        }
                        ?>
                    </select>
                </div>
                <div class="form-group">
                    <label for="estabelecimento_label">Médico Coordenador:</label>                        
                    <select class="form-inline" id="id_medico_coordenador" name="id_medico_coordenador" required>
                        <option selected value="na">
                            Selecione...
                        </option>
                        <?php
                        $sqlmedico_coord = "select id, nome from pcmso_coordenadores where ativo in (1) order by nome asc";
                        foreach ($pdo->query($sqlmedico_coord) as $value) {
                            echo '<option value="' . $value['id'] . '">' . utf8_encode($value['nome']) . '</option>';
                        }
                        ?>
                    </select>
                </div>
                <div class="form-inline" id="caixa_error"></div>                
            </div>            
            <div class="form-group">
                <table class="table table-striped table-bordered">
                    <tr>
                        <td colspan="3" class="text-center text-uppercase"><strong>complementares</strong></td>
                    </tr>
                    <tr>
                        <td class="text-center">ÁCIDO METIL-HIPÚRICO</td>
                        <td class="text-center">HEMOGRAMA</td>
                        <td class="text-center">ÁCIDO MANDÉLICO</td>
                    </tr>
                    <tr>
                        <td class="text-center">
                            <input type="date" id="comp_ACIDO_METIL_HIPURICO" name="comp_ACIDO_METIL_HIPURICO"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_ACIDO_METIL_HIPURICO" name="status_ACIDO_METIL_HIPURICO" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql2 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql2) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                        <td class="text-center">
                            <input type="date" id="comp_HEMOGRAMA" name="comp_HEMOGRAMA"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_HEMOGRAMA" name="status_HEMOGRAMA" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql3 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql3) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                        <td class="text-center">
                            <input type="date" id="comp_ACIDO_MANDELICO" name="comp_ACIDO_MANDELICO"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_ACIDO_MANDELICO" name="status_ACIDO_MANDELICO" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql4 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql4) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">VDRL</td>
                        <td class="text-center">RETICULÓCITOS</td>
                        <td class="text-center">PARASITOLÓGICO FEZES</td>
                    </tr>
                    <tr>
                        <td class="text-center"><input type="date" id="comp_VDRL" name="comp_VDRL"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_VDRL" name="status_VDRL" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql5 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql5) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                        <td class="text-center"><input type="date" id="comp_RETICULOCITOS" name="comp_RETICULOCITOS"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_RETICULOCITOS" name="status_RETICULOCITOS" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql6 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql6) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                        <td class="text-center"><input type="date" id="comp_PARASITOLOGICO_FEZES" name="comp_PARASITOLOGICO_FEZES"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_PARASITOLOGICO_FEZES" name="status_PARASITOLOGICO_FEZES" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql7 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql7) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">CULTURAL DE OROFARINGE</td>
                        <td class="text-center">COPROCULTURA</td>
                        <td class="text-center">MICOLÓGICO DE UNHA</td>
                    </tr>
                    <tr>
                        <td class="text-center"><input type="date" id="comp_CULTURAL_DE_OROFARINGE" name="comp_CULTURAL_DE_OROFARINGE"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_CULTURAL_DE_OROFARINGE" name="status_CULTURAL_DE_OROFARINGE" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql8 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql8) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                        <td class="text-center"><input type="date" id="comp_COPROCULTURA" name="comp_COPROCULTURA"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_COPROCULTURA" name="status_COPROCULTURA" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql9 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql9) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                        <td class="text-center"><input type="date" id="comp_MICOLOGICO_DE_UNHA" name="comp_MICOLOGICO_DE_UNHA"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_MICOLOGICO_DE_UNHA" name="status_MICOLOGICO_DE_UNHA" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql10 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql10) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">AUDIOMETRIA</td>
                        <td class="text-center">ECG</td>
                        <td class="text-center">ACUIDADE VISUAL</td>
                    </tr>
                    <tr>
                        <td class="text-center"><input type="date" id="comp_AUDIOMETRIA" name="comp_AUDIOMETRIA"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_AUDIOMETRIA" name="status_AUDIOMETRIA" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql11 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql11) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                        <td class="text-center"><input type="date" id="comp_ECG" name="comp_ECG"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_ECG" name="status_ECG" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql12 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql12) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                        <td class="text-center"><input type="date" id="comp_ACUIDADE_VISUAL" name="comp_ACUIDADE_VISUAL"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_ACUIDADE_VISUAL" name="status_ACUIDADE_VISUAL" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql13 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql13) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">EEG</td>
                        <td class="text-center">PLAQUETAS</td>
                        <td class="text-center">ERITROGRAMA</td>
                    </tr>
                    <tr>
                        <td class="text-center"><input type="date" id="comp_EEG" name="comp_EEG"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_EEG" name="status_EEG" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql14 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql14) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                        <td class="text-center"><input type="date" id="comp_PLAQUETAS" name="comp_PLAQUETAS"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_PLAQUETAS" name="status_PLAQUETAS" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql15 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql15) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                        <td class="text-center"><input type="date" id="comp_ERITROGRAMA" name="comp_ERITROGRAMA"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_ERITROGRAMA" name="status_ERITROGRAMA" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql16 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql16) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">ÁCIDO TT MUCÔNICO</td>
                        <td class="text-center">GLICEMIA EM JEJUM</td>
                        <td class="text-center">ÁCIDO HIPÚRICO</td>
                    </tr>
                    <tr>
                        <td class="text-center"><input type="date" id="comp_ACIDO_TT_MUCONICO" name="comp_ACIDO_TT_MUCONICO"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_ACIDO_TT_MUCONICO" name="status_ACIDO_TT_MUCONICO" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql17 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql17) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                        <td class="text-center"><input type="date" id="comp_GLICEMIA_EM_JEJUM" name="comp_GLICEMIA_EM_JEJUM"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_GLICEMIA_EM_JEJUM" name="status_GLICEMIA_EM_JEJUM" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql18 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql18) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?></td>
                        <td class="text-center"><input type="date" id="comp_ACIDO_HIPURICO" name="comp_ACIDO_HIPURICO"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_ACIDO_HIPURICO" name="status_ACIDO_HIPURICO" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql19 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql19) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">AVALIAÇÃO PSICOSSOCIAL</td>                    
                    </tr>
                    <tr>
                        <td class="text-center"><input type="date" id="comp_AVALIACAO_PSICOSSOCIAL" name="comp_AVALIACAO_PSICOSSOCIAL"><br><br>
                            <label>Exame: </label>
                            <select class="form-inline" id="status_AVALIACAO_PSICOSSOCIAL" name="status_AVALIACAO_PSICOSSOCIAL" required>
                                <option selected value="na">
                                    Selecione...
                                </option>
                                <?php
                                $sql20 = "select id, complementar from wal_complementares_normal_alterado where status in (1) order by complementar asc";
                                foreach ($pdo->query($sql20) as $value) {
                                    echo '<option value="' . $value['id'] . '">' . $value['complementar'] . '</option>';
                                }
                                Database::disconnect();
                                ?>
                            </select>
                        </td>
                    </tr>
                </table>
                <div class="form-inline" id="complementar_error"></div>
            </div>
        </div>
        <div class="form-group">
            <button class="btn btn-primary btn-danger" id="button" type="button">Fizeram Periódico <span class="glyphicon glyphicon-save" aria-hidden="true"></span></button>
        </div>
    </div>
    <div class="widget-content padding">
        <p class="text-center text-box">Azul -> Foi marcado tanto como correto, <strong>quanto</strong> com erro amiguinho!!</p>
        <p class="text-center text-box">Vermelho -> não recebeu nenhum tipo de marcação!!</p>
    </div>
    <div class="widget-content padding" id="periodico"></div>
</div>