<?php

include '../config/database_mysql.php';
include '../../class/ayuadame.php';
$pdo = Database::connect();
$sql = "select id, razao_social, if(CNES = 0,'N&atilde;o Informado',CNES) as CNES, data_cadastro, cnpj, valor_consulta, valor_consulta_2, valor_consulta_3, data_acerto_2, data_acerto_3 from wal_prestadores where id not in (1,2) order by razao_social asc";
$html = '';
$html = $html . '<table border="1">';
$html = $html . '<thead><tr>';
$html = $html . '<th colspan="4" class="text-center">Nome Prestador</th><th class="text-center">CNES</th><th class="text-center">Cadastro</th>';
$html = $html . '</tr>';
$html = $html . '</thead><tbody>';

$cont = 0;
foreach ($pdo->query($sql) as $value) {
    $html = $html . '<tr>';
    $html = $html . '<td colspan="4"><strong>' . $value['razao_social'] . '</strong></td>';
    $html = $html . '<td><strong>' . $value['CNES'] . '</strong></td>';
    $html = $html . '<td><strong>' . transformaEmDataBrasileira($value['data_cadastro']) . '</strong></td>';
    $html = $html . '</tr>';
    $html = $html . '<td class="text-center text-danger"><small><strong>Valor Consulta</strong></small></td></tr>';

    $id = $cont;
    $html = $html . '<tr class="accordion-toggle">';
    echo '<td>+</td><td>Valor da Consulta</td><td>Valor da Consulta</td><td>Data do Acerto</td><td>Valor da Consulta</td><td>Data do Acerto</td>';
    $sql_medicos_tutu = "select exame_clinico, acido_metil_hipurico, hemograma, acido_mandelico, 
                        vdrl, reticulocitos, parasitologico_fezes, cultural_de_orofaringe, coprocultura, micologico_de_unha,
                        audiometria, ecg, acuidade_visual, eeg, plaquetas, eritrograma, acido_tt_muconico, 
                        glicemia_em_jejum, acido_hipurico from medicos_valores_exames where cnpj = " . $value['cnpj'];
    $qq = $pdo->prepare($sql_medicos_tutu);
    $qq->execute();
    $dataq = $qq->fetch(PDO::FETCH_ASSOC);
    $html = $html . '</tr>';
    $html = $html . '<tr class="accordion-toggle">';
    $html = $html . '<td></td>';
    $html = $html . '<td class="text-center text-danger"><small>R$ ' . transformaEmReal(str_replace(",", ".", $value['valor_consulta'] == NULL ? 0 : $value['valor_consulta'])) . '</small></td>';
    $html = $html . '<td class="text-center text-danger"><small>R$ ' . transformaEmReal(str_replace(",", ".", $value['valor_consulta_2'] == NULL ? 0 : $value['valor_consulta_2'])) . '</small></td>';
    $html = $html . '<td class="text-center text-danger"><small>' . transformaEmDataBrasileira($value['data_acerto_2']) . '</small></td>';
    $html = $html . '<td class="text-center text-danger"><small>R$ ' . transformaEmReal(str_replace(",", ".", $value['valor_consulta_3'] == NULL ? 0 : $value['valor_consulta_3'])) . '</small></td>';
    $html = $html . '<td class="text-center text-danger"><small>' . transformaEmDataBrasileira($value['data_acerto_3']) . '</small></td>';
    $html = $html . '</tr>';
    $html = $html . '<tr><td>';
    $html = $html . '<tr>';
    $html = $html . '<td colspan="3" class="text-center"><small>Valores Exames</small></td>';
    $html = $html . '</tr>';
    $html = $html . '<tr>';
    $html = $html . '<td><small>Exame Cl&iacute;nico</small></td>';
    $html = $html . '<td><small>&Aacute;cido Metil Hip&uacute;rico</small></td>';
    $html = $html . '<td><small>Hemograma</small></td>';
    $html = $html . '</tr>';
    $html = $html . '<tr>';
    $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['exame_clinico'] == NULL ? 0 : $dataq['exame_clinico'])) . '</small></td>';
    $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['acido_metil_hipurico'] == NULL ? 0 : $dataq['acido_metil_hipurico'])) . '</small></td>';
    $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['hemograma'] == NULL ? 0 : $dataq['hemograma'])) . '</small></td>';
    $html = $html . '</tr>';
    $html = $html . '<tr>';
    $html = $html . '<td><small>&Aacute;cido Mand&eacute;lico</small></td>';
    $html = $html . '<td><small>VDRL</small></td>';
    $html = $html . '<td><small>Reticul&oacute;citos</small></td>';
    $html = $html . '</tr>';
    $html = $html . '<tr>';
    $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['acido_mandelico'] == NULL ? 0 : $dataq['acido_mandelico'])) . '</small></td>';
    $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['vdrl'] == NULL ? 0 : $dataq['vdrl'])) . '</small></td>';
    $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['reticulocitos'] == NULL ? 0 : $dataq['reticulocitos'])) . '</small></td>';
    $html = $html . '</tr>';
    $html = $html . '<tr>';
    $html = $html . '<td><small>Parasitol&oacute;gico Fezes</small></td>';
    $html = $html . '<td><small>Cultural de Orofaringe</small></td>';
    $html = $html . '<td><small>Coprocultura</small></td>';
    $html = $html . '</tr>';
    $html = $html . '<tr>';
    $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['parasitologico_fezes'] == NULL ? 0 : $dataq['parasitologico_fezes'])) . '</small></td>';
    $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['cultural_de_orofaringe'] == NULL ? 0 : $dataq['cultural_de_orofaringe'])) . '</small></td>';
    $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['coprocultura'] == NULL ? 0 : $dataq['coprocultura'])) . '</small></td>';
    $html = $html . '</tr>';
    $html = $html . '<tr>';
    $html = $html . '<td><small>Micol&oacute;gico de Unha</small></td>';
    $html = $html . '<td><small>Audiometria</small></td>';
    $html = $html . '<td><small>ECG</small></td>';
    $html = $html . '</tr>';
    $html = $html . '<tr>';
    $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['micologico_de_unha'] == NULL ? 0 : $dataq['micologico_de_unha'])) . '</small></td>';
    $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['audiometria'] == NULL ? 0 : $dataq['audiometria'])) . '</small></td>';
    $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['ecg'] == NULL ? 0 : $dataq['ecg'])) . '</small></td>';
    $html = $html . '</tr>';
    $html = $html . '<tr>';
    $html = $html . '<td><small>Acuidade Visual</small></td>';
    $html = $html . '<td><small>EEG</small></td>';
    $html = $html . '<td><small>Plaquetas</small></td>';
    $html = $html . '</tr>';
    $html = $html . '<tr>';
    $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['acuidade_visual'] == NULL ? 0 : $dataq['acuidade_visual'])) . '</small></td>';
    $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['eeg'] == NULL ? 0 : $dataq['eeg'])) . '</small></td>';
    $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['plaquetas'] == NULL ? 0 : $dataq['plaquetas'])) . '</small></td>';
    $html = $html . '</tr>';
    $html = $html . '<tr>';
    $html = $html . '<td><small>Eritograma</small></td>';
    $html = $html . '<td><small>&Aacute;cido TT Muc&ocirc;nico</small></td>';
    $html = $html . '<td><small>Glicemia em Jejum</small></td>';
    $html = $html . '</tr>';
    $html = $html . '<tr>';
    $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['eritrograma'] == NULL ? 0 : $dataq['eritrograma'])) . '</small></td>';
    $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['acido_tt_muconico'] == NULL ? 0 : $dataq['acido_tt_muconico'])) . '</small></td>';
    $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['glicemia_em_jejum'] == NULL ? 0 : $dataq['glicemia_em_jejum'])) . '</small></td>';
    $html = $html . '</tr>';
    $html = $html . '<tr>';
    $html = $html . '<td colspan="3"><small>&Aacute;cido Hip&uacute;rico</small></td>';
    $html = $html . '</tr>';
    $html = $html . '<tr>';
    $html = $html . '<td colspan="3"><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['acido_hipurico'] == NULL ? 0 : $dataq['acido_hipurico'])) . '</small></td>';
    $html = $html . '</tr>';
    $html = $html . '</td>';
    ++$cont;
}
Database::disconnect();
$html = $html . '</tbody>';
$html = $html . '</table>';
header("Content-type: application/vnd.ms-excel");
header("Content-type: application/force-download");
header("Content-Disposition: attachment; filename=clinicas.xls");
header("Pragma: no-cache");
echo $html;
