<?php

ob_start();
ini_set('display_errors', TRUE);
error_reporting(E_ALL);
include '../config/database_mysql.php';
include '../../class/ayuadame.php';
require_once '../../tools/tcpdf/tcpdf.php';
$pdo = Database::connect();
$sql = "select id, razao_social, if(CNES = 0,'Não Informado',CNES) as CNES, data_cadastro from wal_prestadores where id not in (1,2) order by razao_social asc";
$html = '<div>';
$html = $html . '<table border="1">';
$html = $html . '<thead><tr><th colspan="4">Nome Prestador</th><th>CNES</th><th>Cadastro</th></tr></thead><tbody>';
$cont = 0;
foreach ($pdo->query($sql) as $value) {
    $html = $html . '<tr>';
    $html = $html . '<td colspan="4"><strong>' . $value['razao_social'] . '</strong></td>';
    $html = $html . '<td><strong>' . $value['CNES'] . '</strong></td>';
    $html = $html . '<td><strong>' . transformaEmDataBrasileira($value['data_cadastro']) . '</strong></td>';
    $html = $html . '</tr>';
    $sql_medicos = "select count(*) as tem from wal_medico where id_prestador = " . $value['id'];
    $q = $pdo->prepare($sql_medicos);
    $q->execute();
    $data = $q->fetch(PDO::FETCH_ASSOC);
    if ($data['tem'] > 0) {
        $html = $html . '<tr><td colspan="2"><small><strong>Nome Médico</strong></small></td>';
        $html = $html . '<td><small><strong>CRM</strong></small></td>';
        $html = $html . '<td><small><strong>Conselho</strong></small></td>';
        $html = $html . '<td><small><strong>CNES</strong></small></td>';
        $html = $html . '<td><small><strong>Valor Consulta</strong></small></td></tr>';
        $sql_medico = "select id_medico, nome, crm, conselho, if(CNES = 0,'Não Informado',CNES) as CNES from wal_medico where id_prestador = " . $value['id'];

        foreach ($pdo->query($sql_medico) as $values) {
            $id = $values['id_medico'] . $cont;
            $html = $html . '<tr>';
            $html = $html . '<td></td>';
            $html = $html . '<td><small><strong>' . $values['nome'] . '</strong></small></td>';
            $html = $html . '<td><small>' . $values['crm'] . '</small></td>';
            $html = $html . '<td><small>' . $values['conselho'] . '</small></td>';
            $html = $html . '<td><small>' . $values['CNES'] . '</small></td>';
            $sql_medicos_tutu = "select consulta, exame_clinico, acido_metil_hipurico, hemograma, acido_mandelico, 
                        vdrl, reticulocitos, parasitologico_fezes, cultural_de_orofaringe, coprocultura, micologico_de_unha,
                        audiometria, ecg, acuidade_visual, eeg, plaquetas, eritrograma, acido_tt_muconico, 
                        glicemia_em_jejum, acido_hipurico from medicos_valores_exames where crm = " . $values['crm'];
            $qq = $pdo->prepare($sql_medicos_tutu);
            $qq->execute();
            $dataq = $qq->fetch(PDO::FETCH_ASSOC);
            $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['consulta'] == NULL ? 0 : $dataq['consulta'])) . '</small></td>';
            $html = $html . '</tr>';
            $html = $html . '<tr>';            
            $html = $html . '<td colspan="3"><small>Valores Exames</small></td>';
            $html = $html . '</tr>';
            $html = $html . '<tr>';
            $html = $html . '<td><small>Exame Clínico</small></td>';
            $html = $html . '<td><small>Ácido Metil Hipúrico</small></td>';
            $html = $html . '<td><small>Hemograma</small></td>';
            $html = $html . '</tr>';
            $html = $html . '<tr>';
            $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['exame_clinico'] == NULL ? 0 : $dataq['exame_clinico'])) . '</small></td>';
            $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['acido_metil_hipurico'] == NULL ? 0 : $dataq['acido_metil_hipurico'])) . '</small></td>';
            $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['hemograma'] == NULL ? 0 : $dataq['hemograma'])) . '</small></td>';
            $html = $html . '</tr>';
            $html = $html . '<tr>';
            $html = $html . '<td><small>Ácido Mandélico</small></td>';
            $html = $html . '<td><small>VDRL</small></td>';
            $html = $html . '<td><small>Reticulócitos</small></td>';
            $html = $html . '</tr>';
            $html = $html . '<tr>';
            $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['acido_mandelico'] == NULL ? 0 : $dataq['acido_mandelico'])) . '</small></td>';
            $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['vdrl'] == NULL ? 0 : $dataq['vdrl'])) . '</small></td>';
            $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['reticulocitos'] == NULL ? 0 : $dataq['reticulocitos'])) . '</small></td>';
            $html = $html . '</tr>';
            $html = $html . '<tr>';
            $html = $html . '<td><small>Parasitológico Fezes</small></td>';
            $html = $html . '<td><small>Cultural de Orofaringe</small></td>';
            $html = $html . '<td><small>Coprocultura</small></td>';
            $html = $html . '</tr>';
            $html = $html . '<tr>';
            $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['parasitologico_fezes'] == NULL ? 0 : $dataq['parasitologico_fezes'])) . '</small></td>';
            $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['cultural_de_orofaringe'] == NULL ? 0 : $dataq['cultural_de_orofaringe'])) . '</small></td>';
            $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['coprocultura'] == NULL ? 0 : $dataq['coprocultura'])) . '</small></td>';
            $html = $html . '</tr>';
            $html = $html . '<tr>';
            $html = $html . '<td><small>Micológico de Unha</small></td>';
            $html = $html . '<td><small>Audiometria</small></td>';
            $html = $html . '<td><small>ECG</small></td>';
            $html = $html . '</tr>';
            $html = $html . '<tr>';
            $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['micologico_de_unha'] == NULL ? 0 : $dataq['micologico_de_unha'])) . '</small></td>';
            $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['audiometria'] == NULL ? 0 : $dataq['audiometria'])) . '</small></td>';
            $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['ecg'] == NULL ? 0 : $dataq['ecg'])) . '</small></td>';
            $html = $html . '</tr>';
            $html = $html . '<tr>';
            $html = $html . '<td><small>Acuidade Visual</small></td>';
            $html = $html . '<td><small>EEG</small></td>';
            $html = $html . '<td><small>Plaquetas</small></td>';
            $html = $html . '</tr>';
            $html = $html . '<tr>';
            $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['acuidade_visual'] == NULL ? 0 : $dataq['acuidade_visual'])) . '</small></td>';
            $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['eeg'] == NULL ? 0 : $dataq['eeg'])) . '</small></td>';
            $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['plaquetas'] == NULL ? 0 : $dataq['plaquetas'])) . '</small></td>';
            $html = $html . '</tr>';
            $html = $html . '<tr>';
            $html = $html . '<td><small>Eritograma</small></td>';
            $html = $html . '<td><small>Ácido TT Mucônico</small></td>';
            $html = $html . '<td><small>Glicemia em Jejum</small></td>';
            $html = $html . '</tr>';
            $html = $html . '<tr>';
            $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['eritrograma'] == NULL ? 0 : $dataq['eritrograma'])) . '</small></td>';
            $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['acido_tt_muconico'] == NULL ? 0 : $dataq['acido_tt_muconico'])) . '</small></td>';
            $html = $html . '<td><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['glicemia_em_jejum'] == NULL ? 0 : $dataq['glicemia_em_jejum'])) . '</small></td>';
            $html = $html . '</tr>';
            $html = $html . '<tr>';
            $html = $html . '<td colspan="3"><small>Ácido Hipúrico</small></td>';
            $html = $html . '</tr>';
            $html = $html . '<tr>';
            $html = $html . '<td colspan="3"><small>R$ ' . transformaEmReal(str_replace(",", ".", $dataq['acido_hipurico'] == NULL ? 0 : $dataq['acido_hipurico'])) . '</small></td>';
            $html = $html . '</tr>';            
            ++$cont;
        }
    }
}
Database::disconnect();
$html = $html . '</tbody></table></div>';
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, TRUE, 'UTF-8', FALSE);
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Vítor Dorneles');
$pdf->SetTitle('Clinicas x Medicos');
$pdf->SetSubject('Relatorio analitico e resumo geral');
$pdf->SetKeywords('Aplicacao, Valores, Resumos, Resgates, Medicos');
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
$pdf->SetMargins(2, 2, 2);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
$pdf->setPrintHeader(FALSE);
$pdf->setPrintFooter(TRUE);
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);
$pdf->setFontSubsetting(TRUE);
$pdf->AddPage();
$pdf->writeHTML($html, TRUE, FALSE, TRUE, FALSE, '');
$pdf->Output('Gestao_de_Redes_Clinicas_x_Medicos.pdf', 'D');
ob_end_flush();
